import {
    validateProjectTechnicalEvidence,
    type ProjectTechnicalEvidence,
} from "./project-evidence.ts";

const BANK_CORE_COMMIT = "609e7f567720ec1edf186d5803fbd744e063e34b";
const BANK_WEB_COMMIT = "b7d62497452733894a6f42216ea83e767406b8f3";
const BANK_SERVICE_COMMIT = "7e4beb846c65afc99966a6e4edc9dfd3c9311250";
const BANK_APP_COMMIT = "770afcff097a58cfadf2be47e4c71fca301ca8ac";

const bankCoreUrl = (path: string): string =>
    `https://github.com/gimesha-adikari/bank-core/blob/${BANK_CORE_COMMIT}/${path}`;

const bankWebUrl = (path: string): string =>
    `https://github.com/gimesha-adikari/bank-web/blob/${BANK_WEB_COMMIT}/${path}`;

const bankServiceUrl = (path: string): string =>
    `https://github.com/gimesha-adikari/bank-service/blob/${BANK_SERVICE_COMMIT}/${path}`;

const bankAppUrl = (path: string): string =>
    `https://github.com/gimesha-adikari/bank-app/blob/${BANK_APP_COMMIT}/${path}`;

export const bankingPlatformTechnicalEvidence: ProjectTechnicalEvidence = validateProjectTechnicalEvidence({
    introduction: "Banking Platform is documented as one cross-stack system across four independently versioned repositories: bank-core owns the authoritative Spring Boot backend, bank-web provides the Next.js browser client, bank-service owns the FastAPI KYC service, and bank-app supplies the Kotlin/Android client. This record distinguishes implemented source structure and decision policy from design documents, optional model modules, and untested operational or outcome claims.",
    ownership: [
        {
            boundary: "Spring backend API and persistence",
            owner: "bank-core / Spring backend",
            responsibility: "Own authentication, role checks, customer/account/KYC/wallet feature modules, JPA entities and repositories, and the HTTP API surface.",
            classification: "IMPLEMENTED",
            sources: ["core-build", "spring-security", "account-api", "account-domain", "kyc-case"],
        },
        {
            boundary: "Next.js web client",
            owner: "bank-web / Next.js web",
            responsibility: "Own browser routing, role-gated screens, login state, bearer-token requests, account creation, and account-transaction views through the Next.js/React client.",
            classification: "IMPLEMENTED",
            sources: ["web-package", "web-routes", "web-auth", "web-account-flow"],
        },
        {
            boundary: "Android client",
            owner: "bank-app / Android client",
            responsibility: "Own the Kotlin/Compose application shell, Hilt bindings, Retrofit/Moshi/OkHttp API adapters, account/KYC/wallet flows, local auth-token storage, and app-lock UI.",
            classification: "IMPLEMENTED",
            sources: ["android-build", "android-network", "android-accounts", "android-kyc", "android-storage"],
        },
        {
            boundary: "Identity-verification service",
            owner: "bank-service / FastAPI KYC",
            responsibility: "Own `/api/v1/kyc` component checks and aggregate policy for document classification, OCR, face matching, liveness, and the APPROVE/UNDER_REVIEW/REJECT decision boundary.",
            classification: "IMPLEMENTED",
            sources: ["kyc-aggregate", "kyc-policy", "kyc-config", "kyc-tests"],
        },
    ],
    ipc: [
        {
            boundary: "Next.js web or Android to Spring API",
            behavior: "The web and Android clients call the Spring API over JSON/multipart endpoints and send a Bearer token after login. Route and method guards remain server-owned rather than being treated as client authorization.",
            classification: "IMPLEMENTED",
            sources: ["spring-security", "web-auth", "web-axios", "android-network", "android-auth"],
        },
        {
            boundary: "Spring core to FastAPI KYC",
            behavior: "The KYC orchestrator reads bounded uploaded files, sends an aggregate request to `/api/v1/kyc/aggregate`, accepts an `X-Request-ID`, records returned checks, and maps empty or exceptional ML responses to UNDER_REVIEW.",
            classification: "IMPLEMENTED",
            sources: ["kyc-orchestrator", "kyc-ml-client", "kyc-webclient"],
        },
        {
            boundary: "KYC upload to case",
            behavior: "The Spring API accepts only named document categories and selected image content types, stores an upload owned by the authenticated user, and requires four distinct, correctly typed owned upload IDs before a case is submitted.",
            classification: "IMPLEMENTED",
            sources: ["kyc-upload", "kyc-case", "android-kyc"],
        },
        {
            boundary: "Android unauthorized response",
            behavior: "The Android network layer attaches the stored bearer token and clears it after a 401 response; repository methods expose network/API failures as Result or typed domain exceptions rather than treating a failed request as a successful operation.",
            classification: "IMPLEMENTED",
            sources: ["android-network", "android-auth", "android-accounts", "android-wallet"],
        },
    ],
    workflows: [
        {
            title: "Web or Android login",
            entryPoint: "POST `/api/v1/auth/login` from the Next.js client or bank-app",
            mode: "sync",
            owner: "Spring authentication boundary",
            processing: "The core loads the user, checks active status, authenticates the password through the configured provider, generates a role-bearing JWT, and creates a server-side session record. The clients retain the returned token in their respective auth stores.",
            result: "The client receives a token, then sends it as Bearer authentication to protected routes; invalid or logged-out sessions are rejected by the server filter.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "spring-security", "jwt-auth", "web-auth", "android-auth"],
        },
        {
            title: "Account opening with an opening deposit",
            entryPoint: "POST `/api/v1/accounts` for a customer or `/api/v1/accounts/{id}` for a teller",
            mode: "sync",
            owner: "Spring account service",
            processing: "The service resolves the current or target user, customer, and branch, validates non-negative and account-type minimum deposits, creates an ACTIVE account with a generated unique account number, and writes an opening DEPOSIT transaction when the initial deposit is positive.",
            result: "The API returns an account DTO; the web and Android clients can then request the account transaction history.",
            classification: "IMPLEMENTED",
            sources: ["account-api", "account-service", "account-domain", "android-accounts", "web-account-flow"],
        },
        {
            title: "KYC submission and auto-review",
            entryPoint: "Authenticated KYC upload and submit flow with four upload IDs and consent",
            mode: "sync",
            owner: "Spring KYC case/orchestration boundary",
            processing: "The case service validates ownership, distinctness, and upload types, persists a PENDING case, then the submit controller invokes the orchestrator. A scheduled batch also claims PENDING cases in bounded pages and calls the same review path.",
            result: "The case moves through PENDING/AUTO_REVIEW and receives APPROVED, REJECTED, UNDER_REVIEW, or a further-review state according to the returned aggregate decision and transition rules.",
            classification: "IMPLEMENTED",
            sources: ["kyc-case", "kyc-orchestrator", "kyc-status", "kyc-review", "android-kyc"],
        },
        {
            title: "KYC aggregate decision",
            entryPoint: "POST `/api/v1/kyc/aggregate` with selfie and document inputs",
            mode: "sync",
            owner: "FastAPI KYC policy",
            processing: "The service computes or selects FACE_MATCH, LIVENESS, OCR_ID, and DOC_CLASS results, attaches thresholds, and evaluates the policy. All checks passing produces APPROVE; failed checks produce reasons, with a low face/liveness score below 0.40 producing REJECT and other failures producing UNDER_REVIEW.",
            result: "The response contains a decision, reason codes, and per-check score/pass/details records. This is decision policy evidence, not a population-level accuracy result.",
            classification: "IMPLEMENTED",
            sources: ["kyc-aggregate", "kyc-policy", "kyc-config", "kyc-schemas"],
        },
        {
            title: "Android wallet payment intent",
            entryPoint: "bank-app QR, reload, or bill payment flow",
            mode: "async",
            owner: "bank-app wallet client and Spring wallet service",
            processing: "The Android repository sends an Idempotency-Key, the Spring service creates a PROCESSING PaymentIntent, and the Android view model polls the intent with bounded backoff until success, failure, cancellation, or timeout.",
            result: "The UI exposes explicit creating, processing, succeeded, failed, and canceled states; the audited source does not establish a completed external-provider settlement result.",
            classification: "IMPLEMENTED",
            sources: ["android-wallet", "android-payment-flow", "wallet-service"],
        },
    ],
    lifecycle: [
        {
            phase: "Authenticate",
            actor: "Web or Android client",
            action: "Submit credentials, receive the JWT/role response, and retain the token in the client auth boundary.",
            result: "Protected requests carry a Bearer token; server-side session activity and JWT validation remain required.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "jwt-auth", "web-auth", "android-auth"],
        },
        {
            phase: "Open account",
            actor: "Customer or teller through the Spring API",
            action: "Resolve the customer and branch, validate account type/deposit constraints, generate an account number, persist the account, and persist the opening deposit transaction when applicable.",
            result: "An ACTIVE account DTO and an account-linked opening transaction are available to the client.",
            classification: "IMPLEMENTED",
            sources: ["account-api", "account-service", "account-domain"],
        },
        {
            phase: "Collect KYC inputs",
            actor: "Spring KYC upload boundary and bank-app",
            action: "Upload DOC_FRONT, DOC_BACK, SELFIE, and ADDRESS_PROOF images, enforce type/size/count checks, and return upload IDs.",
            result: "The server retains ownership metadata and the authenticated user can submit only their own correctly typed files.",
            classification: "IMPLEMENTED",
            sources: ["kyc-upload", "kyc-file", "android-kyc"],
        },
        {
            phase: "Submit and claim case",
            actor: "Spring KycCaseService and scheduled orchestrator",
            action: "Require consent, validate four distinct upload IDs, save or reuse a case, transition it to AUTO_REVIEW, and use an atomic processing flag for scheduled claims.",
            result: "A case has an explicit status, timestamps, processing flag, reviewer fields, and a version field for optimistic persistence checks.",
            classification: "IMPLEMENTED",
            sources: ["kyc-case", "kyc-status", "kyc-repository"],
        },
        {
            phase: "Run component checks",
            actor: "FastAPI KYC service",
            action: "Run the configured factory's face, liveness, OCR, and document-classification paths, attach thresholds, and write optional calibration rows when enabled.",
            result: "The aggregate response has per-check scores/pass values and details; source-level thresholds are visible without being presented as calibrated outcomes.",
            classification: "IMPLEMENTED",
            sources: ["kyc-aggregate", "kyc-factory", "kyc-config", "kyc-calibration"],
        },
        {
            phase: "Resolve or review",
            actor: "FastAPI policy and Spring case service",
            action: "Map APPROVE/REJECT/other decisions to Spring statuses; on empty or exceptional ML responses, record an ERROR check and move the case to UNDER_REVIEW.",
            result: "The system preserves a reviewable case state instead of treating an unavailable ML response as an approval.",
            classification: "IMPLEMENTED",
            sources: ["kyc-policy", "kyc-orchestrator", "kyc-review", "kyc-status"],
        },
    ],
    fileLifecycles: [
        {
            title: "KYC document lifecycle",
            description: "The Spring service keeps uploaded documents behind an authenticated owner/admin boundary and passes bounded base64 payloads to the KYC service for a case review.",
            steps: [
                {
                    phase: "Accept",
                    actor: "KycUploadController",
                    action: "Validate category, content type, 10 MB request-file limit, authenticated owner, and daily upload count before storing the file.",
                    result: "A persisted upload ID is returned or the request is rejected with a deliberate client error.",
                    classification: "IMPLEMENTED",
                    sources: ["kyc-upload"],
                },
                {
                    phase: "Associate",
                    actor: "KycCaseService",
                    action: "Require four distinct upload IDs owned by the user and matching the expected document categories.",
                    result: "The case references a known set of document roles rather than arbitrary file IDs.",
                    classification: "IMPLEMENTED",
                    sources: ["kyc-case", "kyc-upload-domain"],
                },
                {
                    phase: "Read and review",
                    actor: "KycAutoReviewOrchestrator",
                    action: "Read each file, reject empty or over-6 MB inputs for the aggregate payload, encode valid bytes, and persist returned checks.",
                    result: "The KYC service sees bounded request data and the core retains check details against the case.",
                    classification: "IMPLEMENTED",
                    sources: ["kyc-orchestrator", "kyc-check"],
                },
            ],
        },
        {
            title: "Android authentication token lifecycle",
            description: "bank-app wraps the token with AES/GCM using an Android Keystore key before storing it in DataStore, then supplies it through the network boundary.",
            steps: [
                {
                    phase: "Receive",
                    actor: "UserRepositoryImpl",
                    action: "Save a successful login response token through TokenManager.",
                    result: "The token enters the encrypted storage adapter rather than being kept as a normal UI field.",
                    classification: "IMPLEMENTED",
                    sources: ["android-auth", "android-storage"],
                },
                {
                    phase: "Encrypt and persist",
                    actor: "TokenManager and Android Keystore",
                    action: "Encrypt the token with AES/GCM and persist the IV plus ciphertext in Preferences DataStore.",
                    result: "Subsequent reads can decrypt the token with the Keystore-backed secret key.",
                    classification: "IMPLEMENTED",
                    sources: ["android-storage", "android-security"],
                },
                {
                    phase: "Attach or clear",
                    actor: "NetworkModule and UnauthorizedHandler",
                    action: "Attach `Authorization: Bearer ...` to requests and clear the token after a 401 response or explicit logout.",
                    result: "Expired/unauthorized sessions do not remain active in the client token store.",
                    classification: "IMPLEMENTED",
                    sources: ["android-network", "android-auth"],
                },
            ],
        },
        {
            title: "Wallet payment intent lifecycle",
            description: "The mobile wallet uses an idempotency key at creation and polls the server-owned PaymentIntent state; the audited source does not establish external settlement completion.",
            steps: [
                {
                    phase: "Create",
                    actor: "bank-app WalletRepository",
                    action: "Send QR/reload/bill details and an Idempotency-Key to the Spring wallet API.",
                    result: "A PaymentIntent identifier is returned or a Result failure is exposed.",
                    classification: "IMPLEMENTED",
                    sources: ["android-wallet", "wallet-service"],
                },
                {
                    phase: "Poll",
                    actor: "PaymentFlowViewModel",
                    action: "Poll the intent with exponential backoff capped at ten seconds for up to two minutes.",
                    result: "The UI reflects PROCESSING, SUCCESS, FAILED, CANCELED, or timeout behavior.",
                    classification: "IMPLEMENTED",
                    sources: ["android-payment-flow"],
                },
                {
                    phase: "External completion",
                    actor: "Out of audited proof",
                    action: "Treat provider settlement, webhook delivery, and end-to-end reconciliation as future evidence work.",
                    result: "No portfolio claim is made about completed external payment settlement.",
                    classification: "NOT TESTED",
                    sources: ["android-payment-flow", "wallet-service"],
                },
            ],
        },
    ],
    processingPaths: [
        {
            title: "KYC component-check pipeline",
            boundary: "FastAPI `/api/v1/kyc/aggregate`",
            behavior: "The aggregate route runs the factory's face, liveness, OCR, and document-classification implementations when inputs exist, adds threshold/pass fields, and returns a check list with details.",
            classification: "IMPLEMENTED",
            limitations: ["The default factory constructs simple face, liveness, OCR, and document-classification implementations; optional ONNX/Tesseract modules exist but are not presented as the default runtime path.", "No population-level accuracy or false-rejection result is published."],
            sources: ["kyc-aggregate", "kyc-factory", "kyc-config", "kyc-schemas"],
        },
        {
            title: "Aggregate decision policy",
            boundary: "FastAPI policy module to Spring KYC status mapping",
            behavior: "All four checks must pass for APPROVE. Any failed check contributes a reason; a face or liveness score below 0.40 produces REJECT, while other failed or missing evidence produces UNDER_REVIEW. Spring maps the result to APPROVED, REJECTED, or UNDER_REVIEW.",
            classification: "IMPLEMENTED",
            limitations: ["The thresholds and policy are code behavior, not evidence that the policy has a measured error rate or is suitable for regulated production use."],
            sources: ["kyc-policy", "kyc-orchestrator", "kyc-status"],
        },
        {
            title: "Optional model/inference modules",
            boundary: "FastAPI feature modules and environment selectors",
            behavior: "The repository contains ONNX face/liveness/portrait modules and Tesseract OCR code, while the current FeatureFactory constructs simple implementations and does not branch on every backend setting. The portfolio therefore describes optional module source without claiming active deployment of a specific model.",
            classification: "DEFERRED",
            limitations: ["Model files, selected deployment configuration, inference reproducibility, and model-level evaluation were not established in the reviewed default branch."],
            sources: ["kyc-factory", "kyc-onnx-face", "kyc-onnx-liveness", "kyc-tesseract"],
        },
        {
            title: "Core financial workflow path",
            boundary: "Spring financial workflows to the immutable ledger",
            behavior: "The Spring financial workflow service validates deposit, withdrawal, and transfer commands, coordinates client idempotency, and delegates the authoritative balance write to the transactional double-entry posting engine. Transaction history remains queryable through the core API.",
            classification: "IMPLEMENTED",
            limitations: ["The portfolio does not claim a completed MySQL-backed integration run, throughput result, or production deployment from source inspection alone."],
            sources: ["ledger-money", "ledger-posting-engine", "financial-workflows", "financial-idempotency", "transaction-query", "account-tests"],
        },
    ],
    failureBoundaries: [
        {
            boundary: "Authentication and session validity",
            trigger: "Missing, invalid, expired, or logged-out JWT/session",
            behavior: "Spring rejects protected requests; bank-app clears its token on a 401 and web auth state can be revalidated through the protected token-validation route.",
            classification: "IMPLEMENTED",
            sources: ["spring-security", "jwt-auth", "android-network", "web-auth"],
        },
        {
            boundary: "KYC upload and case validation",
            trigger: "Unsupported type, over-size file, daily upload limit, duplicate ID, unowned upload, or mismatched document category",
            behavior: "The upload/case boundary returns a deliberate client error and does not submit an arbitrary file set to review.",
            classification: "IMPLEMENTED",
            sources: ["kyc-upload", "kyc-case", "kyc-file"],
        },
        {
            boundary: "KYC service unavailable",
            trigger: "Empty ML response, timeout, connection failure, or exception while calling the FastAPI aggregate endpoint",
            behavior: "The orchestrator records an ERROR check, marks the case UNDER_REVIEW with an unavailable reason, clears processing, and returns the case state instead of approving it.",
            classification: "IMPLEMENTED",
            sources: ["kyc-orchestrator", "kyc-ml-client", "kyc-webclient"],
        },
        {
            boundary: "KYC low-score policy",
            trigger: "A required check fails or face/liveness score falls below the source-level rejection threshold",
            behavior: "The policy returns a reasoned REJECT only for the documented low-score branch; other failed or missing checks remain UNDER_REVIEW.",
            classification: "IMPLEMENTED",
            sources: ["kyc-policy", "kyc-aggregate"],
        },
        {
            boundary: "Android API/network failure",
            trigger: "Non-success HTTP response, IOException, timeout, or invalid response body",
            behavior: "Auth clears on 401; account/KYC/wallet repositories expose typed failures or Result failures, and the payment flow enters FAILED or timeout state rather than claiming success.",
            classification: "IMPLEMENTED",
            sources: ["android-network", "android-accounts", "android-kyc", "android-wallet", "android-payment-flow"],
        },
        {
            boundary: "Account opening validation",
            trigger: "Missing customer/branch, invalid initial deposit, or account-type minimum not met",
            behavior: "The Spring service raises explicit business/resource errors before returning an account DTO.",
            classification: "IMPLEMENTED",
            sources: ["account-service", "account-api", "web-account-flow"],
        },
    ],
    decisions: [
        {
            title: "Group the cross-stack implementation as one portfolio project",
            choice: "Represent four independently versioned repositories as one Banking Platform record.",
            rationale: "Repository ownership follows backend, web, AI/KYC, and Android boundaries while the product remains one multi-client banking system.",
            alternative: "Treating KYC, web, and Android as separate flagship projects would reproduce the old repository-equals-project problem.",
            classification: "ACCEPTED",
            sources: ["core-build", "web-package", "android-build", "kyc-aggregate"],
        },
        {
            title: "Keep authorization server-owned",
            choice: "Use Spring Security route/method guards, JWT validation, server-side session activity, and owner checks for protected resources.",
            rationale: "Client route guards improve navigation but cannot replace the core API's authorization boundary.",
            alternative: "Relying on web/Android role state alone would leave API access decisions outside the authoritative service.",
            classification: "IMPLEMENTED",
            sources: ["spring-security", "jwt-auth", "account-api", "kyc-review", "kyc-file"],
        },
        {
            title: "Use review fallback for KYC uncertainty",
            choice: "Represent non-approval failures and ML unavailability as UNDER_REVIEW unless the explicit low-score rejection branch applies.",
            rationale: "The source preserves a reviewable case state and records reason/check data instead of collapsing every missing or unavailable signal into a rejection or approval.",
            alternative: "A binary approve/reject-only policy was not selected in the audited code path.",
            classification: "IMPLEMENTED",
            sources: ["kyc-policy", "kyc-orchestrator", "kyc-status"],
        },
        {
            title: "Keep mobile auth storage behind an adapter",
            choice: "Store the Android bearer token through AES/GCM and Android Keystore-backed DataStore, then attach it through the network module.",
            rationale: "Token persistence, request decoration, and unauthorized cleanup are kept out of feature screens and repositories.",
            alternative: "Keeping the token in screen state or unencrypted preferences was not the selected token path.",
            classification: "IMPLEMENTED",
            sources: ["android-storage", "android-security", "android-network"],
        },
        {
            title: "Do not publish KYC accuracy outcomes without labeled evidence",
            choice: "Show the implemented checks, thresholds, policy, calibration tooling, and limitations, but do not publish accuracy, false-rejection, or manual-review improvements.",
            rationale: "The reviewed repositories contain policy code and calibration utilities but no labeled evaluation dataset or reproducible report supporting those outcomes.",
            alternative: "Turning threshold values or smoke tests into a quality-rate claim would confuse implementation evidence with measured outcomes.",
            classification: "ACCEPTED",
            sources: ["kyc-config", "kyc-calibration", "kyc-tests"],
        },
        {
            title: "Keep optional model paths visibly optional",
            choice: "Describe ONNX/Tesseract modules as available source paths while identifying the current simple FeatureFactory path as the reviewed default.",
            rationale: "This keeps the portfolio aligned with the actual wiring and avoids implying that model files or a selected inference deployment were verified.",
            alternative: "Naming ArcFace/ONNX as the active production inference path would exceed the source evidence.",
            classification: "DEFERRED",
            sources: ["kyc-factory", "kyc-onnx-face", "kyc-onnx-liveness", "kyc-tesseract"],
        },
    ],
    measurements: [
        {
            claim: "KYC admission and decision thresholds",
            result: "The FastAPI defaults are face 0.85, liveness 0.80, OCR 0.80, and document classification 0.80; the policy's explicit low-score branch uses 0.40 for face or liveness. Spring limits individual uploads to 10 MB and daily uploads to 20 per user.",
            context: "These are source/configuration guardrails and policy constants, not measured quality or capacity results.",
            classification: "IMPLEMENTED",
            method: "Remote default-branch source and configuration inspection.",
            environment: "bank-core main at the recorded public commit; no deployed service configuration was used.",
            sample: "Static defaults and branch conditions; no population sample.",
            limitations: ["Environment variables can override several thresholds and timeouts.", "A threshold is not evidence of accuracy, calibration quality, or suitability for regulated use."],
            sources: ["kyc-config", "kyc-policy", "kyc-upload"],
        },
        {
            claim: "KYC service timeout and bounded payload behavior",
            result: "The Spring ML WebClient defaults to a 1,000 ms connect timeout, 180,000 ms read timeout, and 20 MB in-memory body limit; the orchestrator declines empty files and individual files above 6 MB before base64 encoding.",
            context: "These are integration and input guardrails.",
            classification: "IMPLEMENTED",
            method: "Source/configuration inspection.",
            environment: "bank-core main at the recorded public commit; no live KYC service was started.",
            sample: "Deterministic configured defaults; no workload run.",
            limitations: ["Actual deployment values may differ.", "These settings do not establish throughput, latency percentiles, or horizontal scaling."],
            sources: ["kyc-webclient", "kyc-orchestrator"],
        },
        {
            claim: "KYC accuracy and false-rejection outcomes",
            result: "No labeled evaluation dataset, accuracy report, FAR/FRR report, or reproducible false-rejection comparison was found in the audited default-branch source. Calibration and label-merging tools exist, but no completed labeled report is included.",
            context: "A deliberate evidence gap for face match, liveness, OCR, document classification, and aggregate decisions.",
            classification: "NOT TESTED",
            method: "Bounded search of the KYC source/tests/tools for labeled samples, calibration CSV output, benchmark reports, and population-level quality metrics.",
            environment: "bank-core main at `609e7f567720ec1edf186d5803fbd744e063e34b`; no external dataset or deployment was supplied.",
            sample: "Source, test, and tooling inventory only; no labeled evaluation sample.",
            limitations: ["Do not infer accuracy or false-rejection improvement from thresholds, fixtures, or unit smoke tests.", "A future report needs labeled cohorts, protocol, raw outputs, threshold selection, and error definitions."],
            sources: ["kyc-calibration", "kyc-tests", "kyc-config"],
        },
        {
            claim: "Account opening and transaction integrity",
            result: "The current core source includes BigDecimal monetary validation, immutable double-entry journal posting, materialized customer balances, deposit/withdrawal/transfer workflows, idempotency coordination, transaction history, and a compensating reversal workflow.",
            context: "The source establishes the financial workflow and ledger boundaries; runtime acceptance and MySQL-backed execution remain separate evidence claims.",
            classification: "IMPLEMENTED",
            method: "Source and test inventory inspection of account, transaction, repository, controller, and Spring test paths.",
            environment: "bank-core main at the recorded public commit; no MySQL-backed integration run was performed.",
            sample: "Ledger, workflow, idempotency, reversal, entity/controller source, and two Spring test files; no transaction workload.",
            limitations: ["No portfolio claim is made about production readiness, throughput, regulatory compliance, or external settlement success."],
            sources: ["ledger-money", "ledger-posting-engine", "financial-workflows", "financial-idempotency", "reversal-workflow", "transaction-query", "account-domain", "transaction-domain", "account-service", "transaction-controller", "account-tests"],
        },
        {
            claim: "Android payment state handling",
            result: "The bank-app payment view model polls with an initial one-second delay, exponential backoff capped at ten seconds, and a two-minute limit, then exposes success, failure, canceled, or timeout states.",
            context: "This is an implemented client state machine, not a measured network or provider reliability result.",
            classification: "IMPLEMENTED",
            method: "Source inspection of wallet API, repository, and payment-flow view model.",
            environment: "bank-app main at the recorded public commit; no device or provider session was run.",
            sample: "Deterministic source constants and branches; no network sample.",
            limitations: ["No external payment-provider settlement or webhook test is included in this record.", "No claim is made about success rate or end-to-end payment reliability."],
            sources: ["android-wallet", "android-payment-flow"],
        },
        {
            claim: "Performance and scaling",
            result: "No reproducible load, latency, throughput, memory, or concurrent-user report suitable for publication was found in the audited repositories. Existing timeout, upload-limit, and page structures are documented as guardrails only.",
            context: "The source audit intentionally separates topology and limits from operational measurements.",
            classification: "NOT TESTED",
            method: "Bounded repository search and test inventory inspection across the Spring, Next.js, FastAPI, and Android sources.",
            environment: "Remote public default branches; no shared deployment, database, emulator, or load environment.",
            sample: "Source/docs/tests only; no performance sample.",
            limitations: ["README language and test-file presence are not treated as benchmark evidence.", "A future evidence pass needs a controlled workload, host profile, raw output, and repeatability notes."],
            sources: ["core-build", "web-package", "kyc-tests", "android-build"],
        },
        {
            claim: "Repository test inventory",
            result: "The audited source contains two Spring test files, fourteen Python KYC test files including aggregate/policy-path smoke coverage, and two bank-app template tests. This is an inventory of test material, not a passing cross-repository test result.",
            context: "Test presence is reported separately from executed validation.",
            classification: "ACCEPTED",
            method: "Remote default-branch file inventory and focused test-source inspection.",
            environment: "bank-core, bank-web, bank-service, and bank-app public main snapshots recorded in the source links.",
            sample: "2 Spring files, 14 Python files, 2 Android Kotlin files.",
            limitations: ["The external repositories were not modified or claimed as freshly executed in this portfolio task.", "bank-app tests are template-level and do not establish feature acceptance."],
            sources: ["kyc-tests", "spring-tests", "android-tests"],
        },
    ],
    debuggingStories: [
        {
            title: "Keep an unavailable KYC dependency reviewable",
            symptom: "The Spring orchestrator cannot obtain a usable aggregate response from the FastAPI service.",
            rootCause: "The ML response is empty or the WebClient call raises while the KYC case is being processed.",
            correction: "Persist an ERROR check with the exception detail, mark the case UNDER_REVIEW with `ml_unavailable`, and clear the processing flag in the finally path.",
            verification: "The behavior is directly visible in KycAutoReviewOrchestratorImpl; it is not presented as a measured incident or production recovery result.",
            classification: "IMPLEMENTED",
            limitations: ["No deployed outage drill or retry/queue benchmark was found in the audited source."],
            sources: ["kyc-orchestrator", "kyc-webclient"],
        },
        {
            title: "Clear an Android session after unauthorized access",
            symptom: "A protected Android request returns HTTP 401.",
            rootCause: "The stored bearer token is no longer accepted by the Spring API or the session is no longer active.",
            correction: "NetworkModule's unauthorized handler clears the TokenManager value; feature repositories expose the request failure to the calling UI.",
            verification: "The interceptor, token store, and auth repository paths are present in the audited bank-app source; no device-level test was run here.",
            classification: "IMPLEMENTED",
            limitations: ["No emulator/device session or concurrent-request race test is included."],
            sources: ["android-network", "android-storage", "android-auth"],
        },
        {
            title: "Do not turn missing KYC evidence into a false quality claim",
            symptom: "The repository contains thresholds, smoke fixtures, and a calibration utility but no completed labeled evaluation report.",
            rootCause: "Implementation/configuration evidence and population-level outcome evidence are different boundaries.",
            correction: "Keep the check/policy description, classify outcome quality as NOT TESTED, and defer false-rejection/accuracy language until a labeled evaluation is attached.",
            verification: "The reviewed source contains `calib_log.py`, `calibrate.py`, and KYC tests but no completed labeled report in the audited tree.",
            classification: "ACCEPTED",
            limitations: ["This is a portfolio evidence decision, not a claim about the eventual model quality."],
            sources: ["kyc-calibration", "kyc-tests", "kyc-policy"],
        },
    ],
    codeExcerpts: [
        {
            title: "KYC policy decision states",
            language: "python",
            code: `if not reasons:
    return "APPROVE", reasons

fm = checks.get("FACE_MATCH", {}).get("score")
lv = checks.get("LIVENESS", {}).get("score")
if (fm is not None and fm < 0.40) or (lv is not None and lv < 0.40):
    return "REJECT", reasons

return "UNDER_REVIEW", reasons`,
            explanation: "The policy makes the three decision states and low-score reject boundary explicit; it shows implementation policy rather than a measured accuracy or false-rejection result.",
            source: bankServiceUrl("app/core/policy.py#L29-L37"),
            sourceCommit: BANK_SERVICE_COMMIT,
            limitation: "Thresholds are implementation rules. The audited repository does not establish labeled model quality, FAR/FRR, or false-rejection improvement.",
        },
    ],
    limitations: [
        "Evidence is based on the public pinned snapshots bank-core main at 609e7f567720ec1edf186d5803fbd744e063e34b, bank-web main at b7d62497452733894a6f42216ea83e767406b8f3, bank-service main at 7e4beb846c65afc99966a6e4edc9dfd3c9311250, and bank-app main at 770afcff097a58cfadf2be47e4c71fca301ca8ac. Neither external repository was modified.",
        "The source establishes four independently versioned repositories with Spring, Next.js, FastAPI, and Android boundaries; it does not establish a deployed production topology, banking-grade controls, regulatory compliance, or operational SLO.",
        "No labeled KYC evaluation cohort, accuracy report, FAR/FRR report, false-rejection comparison, or manual-review rate was found. Those outcome claims remain intentionally unpublished.",
        "The current FastAPI FeatureFactory constructs simple face, liveness, OCR, document-classification, and portrait implementations; ONNX/Tesseract source modules and backend settings are not treated as proof of an active model deployment.",
        "The current bank-core source establishes BigDecimal monetary handling, immutable double-entry posting, materialized balances, idempotent deposit/withdrawal/transfer workflows, transaction history, and compensating reversal code. This source evidence does not substitute for a completed MySQL-backed integration run or production acceptance.",
        "Android token encryption and unauthorized cleanup are implemented in source, but the manifest permits cleartext traffic, app-lock PINs are stored through ordinary SharedPreferences, and no device/security audit was performed here.",
        "No reproducible performance, throughput, concurrency, provider-settlement, or horizontal-scaling result is published. Timeout and size values are configuration guardrails only.",
        "The external repository test files were inspected as evidence inventory, not freshly executed as part of the portfolio repository validation.",
    ],
    sources: [
        {
            id: "ledger-money",
            label: "Monetary amount policy",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/ledger/domain/MonetaryAmount.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Immutable BigDecimal monetary value object with explicit customer-input and ledger-storage scales and no binary floating-point path.",
        },
        {
            id: "ledger-posting-engine",
            label: "Double-entry posting and reversal engine",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/ledger/application/impl/PostingEngineImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Transactional balance writer for normal postings and compensating reversals with journal entries and materialized customer balances.",
        },
        {
            id: "financial-workflows",
            label: "Deposit, withdrawal, and transfer workflows",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/application/impl/FinancialWorkflowServiceImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Core financial workflows validate account authority and compose idempotency with the authoritative posting engine.",
        },
        {
            id: "financial-idempotency",
            label: "Financial mutation idempotency coordinator",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/idempotency/application/CoreIdempotencyCoordinator.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Transactional claim coordination for exactly-once deposit, withdrawal, and transfer command execution and replay handling.",
        },
        {
            id: "reversal-workflow",
            label: "Compensating reversal workflow",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/application/impl/ReversalWorkflowImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Server-owned reversal command path that delegates to the posting engine and returns a reversal receipt.",
        },
        {
            id: "transaction-query",
            label: "Transaction history query service",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/application/impl/TransactionQueryServiceImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2026-09-11",
            description: "Core transaction-history query implementation for the authoritative banking API.",
        },
        {
            id: "core-build",
            label: "Spring core build configuration",
            url: bankCoreUrl("build.gradle"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Spring Boot, Java 21, JPA, Security, WebFlux, MySQL, and test dependencies for the core service.",
        },
        {
            id: "spring-security",
            label: "Spring Security configuration",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/modules/common/security/SecurityConfig.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Stateless security filter chain, public auth routes, role gates, BCrypt password encoder, and method security.",
        },
        {
            id: "jwt-auth",
            label: "JWT filter and token utilities",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/modules/common/security/JwtAuthFilter.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Bearer extraction, active-session check, JWT validation, and role authority construction.",
        },
        {
            id: "auth-controller",
            label: "Spring authentication controller",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/auth/interfaces/AuthController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Login, registration, logout, token validation, password, and session creation endpoints.",
        },
        {
            id: "account-api",
            label: "Account controller",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/accounts/interfaces/AccountController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Role-guarded account creation, owner/admin reads, status operations, and transaction-history route.",
        },
        {
            id: "account-service",
            label: "Account service implementation",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/accounts/application/impl/AccountServiceImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Customer/branch resolution, deposit validation, unique account number generation, account persistence, and opening transaction creation.",
        },
        {
            id: "account-domain",
            label: "Account entity",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/accounts/domain/Account.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Account identity, unique account number, status, balance, customer/branch relationships, and timestamps.",
        },
        {
            id: "transaction-domain",
            label: "Transaction entity",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/domain/Transaction.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Persisted transaction type, amount, balance-after, account association, and creation timestamp.",
        },
        {
            id: "transaction-controller",
            label: "Transaction controller",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/transactions/interfaces/TransactionController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Current deposit, withdrawal, transfer, reversal, and transaction-history routes over the core financial workflow boundary.",
        },
        {
            id: "account-tests",
            label: "Spring application test inventory",
            url: bankCoreUrl("src/test/java/com/bankingsystem/core/CoreBankingSystemApplicationTests.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Core Spring test source inspected alongside the KYC integration contract test.",
        },
        {
            id: "web-package",
            label: "Next.js web package",
            url: bankWebUrl("package.json"),
            commit: BANK_WEB_COMMIT,
            date: "2025-09-19",
            description: "Next.js 16, React 19, TypeScript, Tailwind CSS, and the web-client test/build dependencies.",
        },
        {
            id: "web-routes",
            label: "Next.js route composition",
            url: bankWebUrl("app/layout.tsx"),
            commit: BANK_WEB_COMMIT,
            date: "2025-09-19",
            description: "Public and role-gated route composition for customer, admin, teller, manager, and employee surfaces.",
        },
        {
            id: "web-auth",
            label: "Next.js authentication provider",
            url: bankWebUrl("components/auth/AuthProvider.tsx"),
            commit: BANK_WEB_COMMIT,
            date: "2025-09-19",
            description: "Browser token initialization, validation, logout, auth headers, and role state.",
        },
        {
            id: "web-axios",
            label: "typed web API client",
            url: bankWebUrl("lib/api/http.ts"),
            commit: BANK_WEB_COMMIT,
            date: "2025-09-19",
            description: "Configured API client that adds the browser bearer token to requests.",
        },
        {
            id: "web-account-flow",
            label: "Next.js account creation flow",
            url: bankWebUrl("app/(staff)/staff/accounts/new/page.tsx"),
            commit: BANK_WEB_COMMIT,
            date: "2025-09-19",
            description: "Role-aware account creation form, client-side deposit hints, API submission, and transaction-history navigation.",
        },
        {
            id: "kyc-upload",
            label: "KYC upload boundary",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/interfaces/KycUploadController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Allowed upload categories, image content types, 10 MB limit, daily count limit, and authenticated ownership.",
        },
        {
            id: "kyc-file",
            label: "KYC file access boundary",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/interfaces/KycFileController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Owner/admin authorization before reading stored KYC bytes.",
        },
        {
            id: "kyc-case",
            label: "KYC case service and submit controller",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/application/impl/KycCaseServiceImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Distinct owned upload validation, case creation/reuse, consent submission, and status transitions.",
        },
        {
            id: "kyc-status",
            label: "KYC status transitions",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/modules/common/enums/KycStatus.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Explicit pending, auto-review, under-review, more-information, approved, and rejected transitions.",
        },
        {
            id: "kyc-case-domain",
            label: "KYC case persistence model",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/domain/KycCase.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Case status, upload references, reviewer fields, processing flag, timestamps, and optimistic version field.",
        },
        {
            id: "kyc-repository",
            label: "KYC case repository",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/domain/repository/KycCaseRepository.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Status queries, candidate paging, and atomic processing-claim update.",
        },
        {
            id: "kyc-upload-domain",
            label: "KYC upload entity",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/domain/KycUpload.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Upload category, checksum/path metadata, size, owner, and timestamp fields.",
        },
        {
            id: "kyc-check",
            label: "KYC check entity",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/domain/KycCheck.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Per-check type, score, pass value, details JSON, case association, and timestamp.",
        },
        {
            id: "kyc-orchestrator",
            label: "KYC auto-review orchestrator",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/application/impl/KycAutoReviewOrchestratorImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Scheduled batch, bounded case claiming, file reads, FastAPI call, check persistence, decision mapping, and failure fallback.",
        },
        {
            id: "kyc-ml-client",
            label: "Spring to FastAPI KYC client",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/integration/MlKycClient.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Aggregate request/response DTOs and `/api/v1/kyc/aggregate` WebClient call.",
        },
        {
            id: "kyc-webclient",
            label: "KYC WebClient configuration",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/integration/MlWebClientConfig.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Configurable KYC base URL, connection/read timeouts, and maximum in-memory body size.",
        },
        {
            id: "kyc-review",
            label: "KYC admin review boundary",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/kyc/interfaces/KycReviewController.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Admin-only case listing, decision transitions, and check inspection.",
        },
        {
            id: "kyc-aggregate",
            label: "FastAPI KYC aggregate route",
            url: bankServiceUrl("app/api/v1/kyc.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Component check composition, portrait fallback, thresholds, request IDs, calibration logging, and aggregate response.",
        },
        {
            id: "kyc-policy",
            label: "FastAPI KYC aggregate policy",
            url: bankServiceUrl("app/core/policy.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Reason codes and APPROVE/UNDER_REVIEW/REJECT policy branches.",
        },
        {
            id: "kyc-config",
            label: "FastAPI KYC configuration",
            url: bankServiceUrl("app/core/config.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Default thresholds, backend settings, portrait mode, and calibration-log configuration.",
        },
        {
            id: "kyc-factory",
            label: "FastAPI feature factory",
            url: bankServiceUrl("app/features/factory.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Reviewed default feature construction for face, liveness, OCR, document classification, and portrait extraction.",
        },
        {
            id: "kyc-schemas",
            label: "FastAPI KYC schemas",
            url: bankServiceUrl("app/api/v1/schemas.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Input payload and aggregate/check response structures.",
        },
        {
            id: "kyc-onnx-face",
            label: "Optional ONNX face module",
            url: bankServiceUrl("app/features/face/onnx_ort.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "ONNX/OpenCV face detection and matching implementation present in source but not treated as the default factory path.",
        },
        {
            id: "kyc-onnx-liveness",
            label: "Optional ONNX liveness module",
            url: bankServiceUrl("app/features/liveness/fas_onnx.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "ONNX anti-spoof implementation and threshold handling present in source.",
        },
        {
            id: "kyc-tesseract",
            label: "Optional Tesseract OCR module",
            url: bankServiceUrl("app/features/ocr/tesseract.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Tesseract preprocessing and structured field extraction implementation present in source.",
        },
        {
            id: "kyc-calibration",
            label: "KYC calibration tooling",
            url: bankServiceUrl("app/tools/calibrate.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "CSV grouping, labeled GOOD/BAD summaries, threshold suggestions, and estimated FAR/FRR calculation tooling; no completed report was found.",
        },
        {
            id: "kyc-tests",
            label: "FastAPI KYC test inventory",
            url: bankServiceUrl("tests/test_aggregate.py"),
            commit: BANK_SERVICE_COMMIT,
            date: "2025-09-19",
            description: "Aggregate and component smoke tests, portrait fallback/provided paths, and backend/test fixtures; inventory only for this portfolio record.",
        },
        {
            id: "spring-tests",
            label: "Spring KYC contract test inventory",
            url: bankCoreUrl("src/test/java/com/bankingsystem/core/features/kyc/integration/KycMlContractIT.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Contract fixture expectations for APPROVE, UNDER_REVIEW, and REJECT when a live ML service is available.",
        },
        {
            id: "android-build",
            label: "bank-app Android build",
            url: bankAppUrl("app/build.gradle.kts"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Kotlin/Android, Compose, Retrofit, OkHttp logging, DataStore, Biometric, Camera, and Hilt dependencies.",
        },
        {
            id: "android-network",
            label: "bank-app network module",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/app/di/NetworkModule.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Retrofit/OkHttp construction, bearer-token interceptor, unauthorized cleanup, timeouts, and API bindings.",
        },
        {
            id: "android-auth",
            label: "bank-app auth API and repository",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/features/auth/integration/repository/UserRepositoryImpl.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Login, token persistence, validation, logout cleanup, and network/API failure mapping.",
        },
        {
            id: "android-accounts",
            label: "bank-app account API/repository",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/features/accounts/integration/repository/AccountRepositoryImpl.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Account opening, current-user account list, transaction-history retrieval, and typed error mapping.",
        },
        {
            id: "android-kyc",
            label: "bank-app KYC API/repository",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/features/kyc/integration/repository/KycRepositoryImpl.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Multipart upload of four KYC image types, consented case submission, status, and check retrieval.",
        },
        {
            id: "android-storage",
            label: "bank-app token storage",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/core/modules/common/storage/TokenManager.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "AES/GCM token encryption, DataStore persistence, decryption, and clearing.",
        },
        {
            id: "android-security",
            label: "bank-app Keystore encryption",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/core/modules/common/security/KeyStoreManager.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Android Keystore AES key generation and GCM parameters used by token storage.",
        },
        {
            id: "android-wallet",
            label: "bank-app wallet API/repository",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/features/wallet/integration/repository/WalletRepositoryImpl.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Card sessions, QR/reload/bill payment intents, idempotency keys, and result mapping.",
        },
        {
            id: "android-payment-flow",
            label: "bank-app payment state flow",
            url: bankAppUrl("app/src/main/java/com/bankingsystem/mobile/features/wallet/interfaces/ui/PaymentFlowViewModel.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "Payment intent polling, bounded backoff, terminal states, and timeout behavior.",
        },
        {
            id: "android-tests",
            label: "bank-app test inventory",
            url: bankAppUrl("app/src/test/java/com/bankingsystem/mobile/ExampleUnitTest.kt"),
            commit: BANK_APP_COMMIT,
            date: "2025-09-17",
            description: "The audited repository contains the default unit and instrumented test templates; no feature-level acceptance is inferred.",
        },
        {
            id: "wallet-service",
            label: "Spring wallet service",
            url: bankCoreUrl("src/main/java/com/bankingsystem/core/features/wallet/application/impl/WalletServiceImpl.java"),
            commit: BANK_CORE_COMMIT,
            date: "2025-09-19",
            description: "Server-side idempotency wrapper and PaymentIntent creation for QR, reload, and bill flows.",
        },
    ],
});
