import {
    validateProjectTechnicalEvidence,
    type ProjectTechnicalEvidence,
} from "./project-evidence.ts";

const PLATEN_PDF_FRONTEND_COMMIT = "70db8e8a5a1466ddb154112ed1ddecee6e6cb57e";
const PLATEN_PDF_BACKEND_COMMIT = "9faae1a42155843e0e5a6e472d6a4109ccaa25a8";
const PLATEN_PDF_WORKER_COMMIT = "9d38852e7ca1e7b657f7f644823d400553886ff0";
const PLATEN_DOCUMENT_COMMIT = "a5a14413ded0daa93a5839b86554f1fe67d92a93";

const sourceUrl = (repository: string, commit: string, path: string): string =>
    `https://github.com/gimesha-adikari/${repository}/blob/${commit}/${path}`;

export const platenPdfTechnicalEvidence: ProjectTechnicalEvidence = validateProjectTechnicalEvidence({
    introduction: "Platen PDF is documented here as a multi-service document product: the web workspace owns browser interaction, the Go API owns application and file boundaries, the Python worker owns selected processing jobs, and platen-document remains a related local-first engine rather than a required application service.",
    ownership: [
        {
            boundary: "Web workspace",
            owner: "pdfnest web application",
            responsibility: "Own tool selection, browser-side file/workspace state, configured API requests, preview presentation, and local result/download state.",
            classification: "IMPLEMENTED",
            sources: ["frontend-api", "frontend-workspace"],
        },
        {
            boundary: "Application and file boundary",
            owner: "pdfnest-backend",
            responsibility: "Own HTTP routes, identity and quota checks, PDF/upload validation, temporary staging, worker dispatch, task state, artifact access, and cleanup coordination.",
            classification: "IMPLEMENTED",
            sources: ["backend-main", "backend-validation", "backend-upload", "backend-task", "backend-download"],
        },
        {
            boundary: "Processing boundary",
            owner: "pdfnest-worker",
            responsibility: "Own selected Python/FastAPI processing routes, Dramatiq actors, Redis-backed job state, OCR/document engines, progress, cancellation, and worker-side artifacts.",
            classification: "IMPLEMENTED",
            sources: ["worker-main", "worker-jobs", "worker-store", "worker-actors"],
        },
        {
            boundary: "Related local engine",
            owner: "platen-document SDK",
            responsibility: "Provide independently importable local PDF/OCR/document APIs. It does not own Platen PDF authentication, queues, durable storage, billing, or HTTP application routing.",
            classification: "IMPLEMENTED",
            sources: ["sdk-api", "sdk-architecture"],
        },
    ],
    ipc: [
        {
            boundary: "Browser to Go API",
            behavior: "The web application posts FormData or JSON to the configured API origin. Immediate operations return a binary response; job-oriented operations return a submission/task reference rather than exposing the worker to the browser.",
            classification: "IMPLEMENTED",
            sources: ["frontend-api", "frontend-jobs"],
        },
        {
            boundary: "Go API to worker",
            behavior: "The backend calls the worker over an authenticated HTTP boundary, using signed requests and streaming multipart bodies where a local file is sent; the browser does not call the worker directly.",
            classification: "IMPLEMENTED",
            sources: ["backend-worker", "backend-editor-worker", "backend-ocr"],
        },
        {
            boundary: "Job state and artifact boundary",
            behavior: "Worker jobs use queued/running/terminal states and artifact references; the worker mirrors canonical state into the legacy Go task shape so existing status/download routes can continue to serve owner-scoped results.",
            classification: "IMPLEMENTED",
            sources: ["worker-jobs", "worker-store", "backend-task", "backend-download"],
        },
        {
            boundary: "Preview session boundary",
            behavior: "The backend prepares a temporary preview input, creates or reuses an owner-and-content-keyed worker render session, requests a page image, and recreates the worker session once when a cached render session fails.",
            classification: "IMPLEMENTED",
            sources: ["backend-preview", "worker-main"],
        },
    ],
    workflows: [
        {
            title: "Immediate document operation",
            entryPoint: "Browser multipart request to short-form structure, optimization, or security routes",
            mode: "sync",
            owner: "Go API and the selected document handler",
            processing: "The API validates and stages the upload, then the route either completes within the backend or delegates a specialized operation before returning the response body.",
            result: "A binary response is returned to the browser and the frontend owns the local result state.",
            classification: "IMPLEMENTED",
            sources: ["frontend-api", "backend-main", "backend-validation"],
        },
        {
            title: "Direct OCR response",
            entryPoint: "POST /api/ocr/extract-text or /api/ocr/to-text-pdf",
            mode: "sync",
            owner: "Go API with the worker OCR boundary",
            processing: "The API validates the PDF or image set, calls the worker-backed OCR service, and keeps the response tied to the request context; direct worker OCR uses a bounded in-process admission gate.",
            result: "Text or a searchable PDF is streamed back for the request, with temporary input/output cleanup in the request lifecycle.",
            classification: "IMPLEMENTED",
            sources: ["backend-ocr", "worker-ocr"],
        },
        {
            title: "Long-running processing job",
            entryPoint: "Async OCR, editor, markup, and PDF-to-Markdown routes",
            mode: "async",
            owner: "Go task boundary and Python worker actors",
            processing: "The API registers a task, persists or references the source, dispatches a named worker actor, and returns while the worker claims capacity, reports progress, and writes an artifact.",
            result: "The client receives an accepted submission and later uses status and owner-scoped download paths for the terminal result.",
            classification: "IMPLEMENTED",
            sources: ["frontend-jobs", "backend-markdown", "backend-ocr", "worker-router", "worker-actors"],
        },
        {
            title: "Page preview",
            entryPoint: "Preview session creation and page-render requests",
            mode: "preview",
            owner: "Go preview service and worker render session",
            processing: "The backend hashes the prepared PDF for an owner-scoped session, asks the worker for only the requested page, and recreates a failed cached session before retrying the render.",
            result: "A page image is returned for workspace preview; it is not treated as the final downloadable processing artifact.",
            classification: "IMPLEMENTED",
            sources: ["backend-preview"],
        },
        {
            title: "Optional local document engine",
            entryPoint: "Explicit internal/sdk engine selectors at the worker/application boundary",
            mode: "sync",
            owner: "Application adapter and platen-document SDK",
            processing: "The application may select the standalone SDK for supported consumers; the SDK processes local paths with native/scanned routing, OCR, structured extraction, rendering, and cooperative callbacks.",
            result: "The application keeps the job, storage, authorization, and lifecycle contract outside the SDK; explicit SDK selection has no implicit runtime fallback.",
            classification: "ACCEPTED",
            sources: ["sdk-api", "sdk-architecture"],
        },
    ],
    lifecycle: [
        {
            phase: "Receive and validate",
            actor: "Go API",
            action: "Accept the multipart upload, stage it in the dedicated temporary workspace, validate the PDF signature and operation-specific page limit, and resolve the request identity.",
            result: "Malformed, empty, unreadable, or over-limit input is rejected before processing begins.",
            classification: "IMPLEMENTED",
            sources: ["backend-upload", "backend-validation", "worker-ocr"],
        },
        {
            phase: "Choose response mode",
            actor: "Route and application policy",
            action: "Select an immediate response, a queued task, or a page-scoped preview based on the operation rather than forcing every route through the same job path.",
            result: "Short request work can return directly while long-running or progress-bearing work receives a durable job boundary.",
            classification: "IMPLEMENTED",
            sources: ["frontend-api", "frontend-jobs", "backend-main", "backend-markdown"],
        },
        {
            phase: "Persist and dispatch",
            actor: "Go API",
            action: "For async work, write the source to an application-controlled storage key, create task state and download capability data, then submit the named worker actor.",
            result: "The request returns an accepted task reference, or marks the task failed and releases the reservation when dispatch/storage setup fails.",
            classification: "IMPLEMENTED",
            sources: ["backend-markdown", "backend-task", "backend-worker"],
        },
        {
            phase: "Claim and process",
            actor: "Worker actor",
            action: "Claim the queued job, acquire the configured execution lease, download the source into a temporary path, run the selected engine, report progress, and observe cancellation.",
            result: "The worker records a terminal success, cancellation, or failure with an artifact reference and bounded diagnostic fields.",
            classification: "IMPLEMENTED",
            sources: ["worker-store", "worker-actors", "worker-config"],
        },
        {
            phase: "Serve and clean up",
            actor: "Go API and worker storage boundaries",
            action: "Mirror terminal state, authorize completed-artifact download by owner or capability token, stream the artifact through a temporary download path when needed, and remove request/job temporary files.",
            result: "The result is available only through the intended completion and ownership boundary; expired or removed artifacts return an explicit unavailable response.",
            classification: "IMPLEMENTED",
            sources: ["worker-store", "backend-download", "backend-upload", "backend-ocr"],
        },
    ],
    fileLifecycles: [
        {
            title: "Synchronous request file",
            description: "Immediate routes keep the upload in a private request workspace and remove temporary input/output files when the handler returns or fails.",
            steps: [
                {
                    phase: "Stage",
                    actor: "Go upload middleware",
                    action: "Copy the multipart file into the dedicated temp directory using a UUID-prefixed name and restrictive file permissions.",
                    result: "The handler receives a server-owned path rather than trusting a caller-controlled path.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-upload"],
                },
                {
                    phase: "Process",
                    actor: "Go handler and worker boundary",
                    action: "Validate the PDF, run the selected operation, and keep worker multipart transfer streamed where delegation is required.",
                    result: "The response is produced without making the browser responsible for backend filesystem state.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-validation", "backend-worker", "backend-ocr"],
                },
                {
                    phase: "Return and remove",
                    actor: "Request cleanup",
                    action: "Send the result body or file response and remove staged input and temporary output paths in deferred/finally cleanup.",
                    result: "Synchronous artifacts are not represented as durable portfolio-level project files.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-upload", "backend-ocr", "worker-ocr"],
                },
            ],
        },
        {
            title: "Asynchronous source and result",
            description: "Queued work separates durable job references from local worker paths and uses object-storage keys for the source/result boundary where configured.",
            steps: [
                {
                    phase: "Upload to source key",
                    actor: "Go API storage boundary",
                    action: "Validate the staged upload and persist the source under an application-controlled job key before actor dispatch.",
                    result: "The worker can retrieve the source without receiving a browser filesystem path.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-markdown", "backend-storage"],
                },
                {
                    phase: "Materialize locally",
                    actor: "Python worker",
                    action: "Download the source object into a worker-owned temporary path, process it, and upload the output artifact under a job-scoped key.",
                    result: "Job state references an artifact key rather than exposing the worker's local path.",
                    classification: "IMPLEMENTED",
                    sources: ["worker-actors", "worker-storage"],
                },
                {
                    phase: "Download and expire",
                    actor: "Go task/download boundary",
                    action: "Require terminal completion and owner/token authorization, materialize an object-storage artifact into a temporary download path when necessary, and remove that path after response handling.",
                    result: "Expired, missing, or unauthorized results do not become anonymous file reads.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-download", "backend-task"],
                },
            ],
        },
        {
            title: "Preview derivative",
            description: "Preview rendering uses a temporary derivative and an owner/content-keyed worker session instead of treating a preview image as the final document artifact.",
            steps: [
                {
                    phase: "Prepare and fingerprint",
                    actor: "Go preview service",
                    action: "Write the upload to a temporary PDF path, hash it with the requesting identity, and reuse an existing preview session when available.",
                    result: "The same owner and source can reuse a render session without sharing it across identities.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-preview"],
                },
                {
                    phase: "Render page",
                    actor: "Worker render session",
                    action: "Request the selected page at the requested scale and touch the session on success.",
                    result: "The browser receives a page image for inspection while the source remains application-owned.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-preview", "frontend-api"],
                },
                {
                    phase: "Recover and clean",
                    actor: "Go preview service",
                    action: "Delete a failed cached session, recreate it once, retry the page render, and run temporary-file cleanup after the request.",
                    result: "A stale worker render session does not permanently poison the current preview request.",
                    classification: "IMPLEMENTED",
                    sources: ["backend-preview"],
                },
            ],
        },
    ],
    processingPaths: [
        {
            title: "Native/scanned OCR routing",
            boundary: "platen-document engine and worker OCR adapter",
            behavior: "The default route preserves validated native text when appropriate and uses OCR when required; FORCE_OCR is an explicit policy rather than the default.",
            classification: "IMPLEMENTED",
            limitations: ["The reviewed source establishes routing behavior, not a universal accuracy or latency number."],
            sources: ["worker-ocr", "sdk-api", "sdk-architecture"],
        },
        {
            title: "Searchable PDF rendering",
            boundary: "OCR result to searchable-PDF renderer",
            behavior: "An existing OCR result can be passed into the searchable-PDF renderer, avoiding a second OCR pass; the output is independently validated by the SDK renderer boundary.",
            classification: "IMPLEMENTED",
            limitations: ["No cross-device rendering or throughput measurement is published here."],
            sources: ["sdk-api"],
        },
        {
            title: "Page-scoped OCR preview",
            boundary: "Worker OCR V2 preview route",
            behavior: "Preview input can be reduced to one selected page, with request-byte and page-count guards, then projected back to the original page index in the response.",
            classification: "IMPLEMENTED",
            limitations: ["This is a bounded preview path, not evidence that full-document OCR is cheap or universally fast."],
            sources: ["worker-ocr-v2"],
        },
        {
            title: "Explicit SDK integration selector",
            boundary: "Application consumer adapter to platen-document",
            behavior: "Supported consumers can select the SDK through explicit engine selectors; the standalone SDK remains independently usable and does not import application jobs, queues, or storage.",
            classification: "ACCEPTED",
            limitations: ["Selector coverage differs by consumer; the reviewed architecture documents some application paths as internal-only."],
            sources: ["sdk-architecture", "sdk-api"],
        },
    ],
    failureBoundaries: [
        {
            boundary: "Input validation",
            trigger: "Empty/non-PDF upload, unreadable document, unsupported content type, or operation-specific page/byte limit exceeded",
            behavior: "The API or worker rejects the input with an explicit client error before processing or removes a partially staged file on failure.",
            classification: "IMPLEMENTED",
            sources: ["backend-validation", "worker-ocr-v2", "backend-upload"],
        },
        {
            boundary: "Worker unavailable or dispatch failure",
            trigger: "The backend cannot reach the worker or the worker rejects a submitted actor",
            behavior: "The request receives a deliberate gateway/error response; async setup marks the task failed and releases the reservation rather than leaving an apparently successful job without a processor.",
            classification: "IMPLEMENTED",
            sources: ["backend-markdown", "backend-worker", "frontend-api"],
        },
        {
            boundary: "Cancellation and stalled execution",
            trigger: "Client disconnect, user cancellation, actor cancellation request, or worker progress exceeding the configured stale-job window",
            behavior: "Cancellation is propagated where supported, terminal cancellation/failure is recorded, leases are released, and stale jobs transition to failure with an explicit reason.",
            classification: "IMPLEMENTED",
            sources: ["backend-ocr", "worker-store", "worker-actors", "frontend-jobs"],
        },
        {
            boundary: "Artifact access and expiry",
            trigger: "Download requested before completion, by the wrong owner, without a valid capability token, or after the backing object has been removed",
            behavior: "The download boundary returns not-found, forbidden, or gone responses and only serves completed artifacts through the owner/token check.",
            classification: "IMPLEMENTED",
            sources: ["backend-download", "backend-task", "worker-store"],
        },
        {
            boundary: "Engine configuration and availability",
            trigger: "Selected OCR/document engine is unavailable or explicitly configured with an invalid selector",
            behavior: "Worker/API error codes describe engine unavailability or invalid configuration; the SDK architecture does not imply an invisible fallback when the SDK is explicitly selected.",
            classification: "ACCEPTED",
            sources: ["worker-config", "worker-ocr-v2", "sdk-architecture"],
        },
    ],
    decisions: [
        {
            title: "Keep the browser at the Go API boundary",
            choice: "The web application talks to the configured backend origin and never treats the worker as a public browser dependency.",
            rationale: "Identity, validation, storage, quotas, and worker credentials remain server-owned while the browser keeps a simple tool/workspace contract.",
            alternative: "Direct browser-to-worker calls were not chosen because they would expose a processing boundary and bypass the application-owned file/task controls.",
            classification: "ACCEPTED",
            sources: ["frontend-api", "backend-main", "backend-worker"],
        },
        {
            title: "Use response mode per workload",
            choice: "Keep direct responses for bounded request work, queued jobs for long-running/progress-bearing operations, and a separate preview path for page inspection.",
            rationale: "The user experience and resource lifetime differ between a returned blob, a cancellable job, and a page image preview.",
            alternative: "Queueing every operation was not treated as the current design because several routes intentionally return synchronously.",
            classification: "IMPLEMENTED",
            sources: ["frontend-api", "backend-main", "backend-ocr", "backend-markdown", "backend-preview"],
        },
        {
            title: "Separate async artifacts from local worker paths",
            choice: "Async jobs use job-scoped source/result references and owner-aware download routes rather than returning worker filesystem paths to the client.",
            rationale: "The job can outlive the request while storage, authorization, cleanup, and artifact expiry stay explicit.",
            alternative: "Returning a local temp path to the browser was rejected by the server-owned file boundary.",
            classification: "IMPLEMENTED",
            sources: ["backend-markdown", "backend-download", "worker-store"],
        },
        {
            title: "Keep platen-document optional and standalone",
            choice: "Treat platen-document as a related local-first SDK selected through explicit application adapters, not as a required Platen PDF web/API/worker service.",
            rationale: "The SDK can be tested and used locally while the application retains jobs, queues, storage, auth, billing, and UI concerns.",
            alternative: "Merging the SDK into the product runtime or presenting it as a mandatory service would misstate its documented architecture.",
            classification: "ACCEPTED",
            sources: ["sdk-api", "sdk-architecture"],
        },
        {
            title: "Publish guardrails, not capacity claims",
            choice: "Expose implemented byte/page/concurrency/retention guardrails and keep throughput, latency, scalability, and production-capacity claims deferred until controlled evidence exists.",
            rationale: "Source defaults demonstrate boundaries and failure behavior, but they are not a substitute for a repeatable workload benchmark or production measurement.",
            alternative: "Turning configuration limits into a universal capacity claim was rejected as unsupported.",
            classification: "ACCEPTED",
            sources: ["backend-main", "worker-config", "worker-store", "worker-ocr", "sdk-architecture"],
        },
    ],
    measurements: [
        {
            claim: "Request and document guardrails",
            result: "The reviewed defaults include a 100 MB Go API body limit; OCR/convert routes commonly default to 150 pages; worker OCR V2 defaults to 100 MB and 150 pages.",
            context: "These are implemented admission boundaries, not throughput or maximum-capacity measurements.",
            classification: "IMPLEMENTED",
            method: "Default-branch source and configuration inspection.",
            environment: "Verified remote default-branch source for the web/API/worker repositories.",
            sample: "Deterministic configured defaults at the audited commits; no workload sample.",
            limitations: ["Environment variables can change the limits.", "A limit does not establish processing speed or a safe universal document size."],
            sources: ["backend-main", "backend-validation", "worker-ocr-v2"],
        },
        {
            claim: "Job retention and stale-job windows",
            result: "Worker jobs default to a 24-hour Redis TTL and a 180-second stale-running transition; the legacy Go task mirror uses a one-hour TTL and a 15-minute stale-task default.",
            context: "Retention and stale-state behavior are part of the job contract and may be overridden by environment configuration.",
            classification: "IMPLEMENTED",
            method: "Source/config inspection of worker job storage and Go task registry.",
            environment: "Verified remote default-branch source; configured defaults rather than deployed environment values.",
            sample: "Static configuration values; no production expiration experiment.",
            limitations: ["This does not prove object-storage retention or user-visible availability for every deployment.", "The legacy mirror and worker job record have different default windows."],
            sources: ["worker-config", "worker-store", "backend-task"],
        },
        {
            claim: "Execution admission bounds",
            result: "Worker defaults include four global heavy executions, two per identity, and a 600-second heavy lease; direct OCR routes use a default in-process semaphore of two.",
            context: "These settings make resource admission explicit but are not a tested concurrency capacity guarantee.",
            classification: "IMPLEMENTED",
            method: "Source/config inspection.",
            environment: "Verified remote default-branch defaults; no production load environment.",
            sample: "Static configuration values; no load-test run used for this portfolio record.",
            limitations: ["Deployment configuration and document shape affect actual capacity.", "No claim is made about sustained throughput, latency, or horizontal scaling."],
            sources: ["worker-config", "worker-ocr", "worker-store"],
        },
        {
            claim: "Quantitative capacity and throughput",
            result: "No portable benchmark output, production throughput number, or repeatable end-to-end latency figure was found in the reviewed default-branch material, so no numeric performance claim is published.",
            context: "The evidence boundary is deliberate: configuration guardrails are shown separately from measured workload results.",
            classification: "NOT TESTED",
            method: "Bounded search of the four default-branch repositories for benchmark output, profiling captures, timing logs, and load-test results suitable for portfolio publication.",
            environment: "Remote default branches audited at their recorded commits; no shared deployment or controlled benchmark environment.",
            sample: "Source/docs/test inventory only; no quantitative workload sample.",
            limitations: ["A future evidence pass would need a controlled document corpus, host profile, concurrency plan, raw output, and repeatability notes.", "README adjectives and test-file presence were not treated as measurements."],
            sources: ["frontend-api", "backend-main", "worker-config", "sdk-architecture"],
        },
    ],
    debuggingStories: [
        {
            title: "Recovering a stale preview render session",
            symptom: "A cached worker preview session can fail when the worker-side session is no longer usable while the backend still has an owner/content mapping.",
            rootCause: "The backend preview cache can outlive the worker render session it points to.",
            correction: "Delete the failed mapping, create a fresh worker preview session, store the new owner/content association, and retry the requested page once.",
            verification: "The recovery path is explicit in the audited preview service source; no browser screenshot or deployed failure injection is claimed.",
            classification: "IMPLEMENTED",
            limitations: ["Source inspection does not establish how often this happens in production.", "No end-to-end visual regression run was used as evidence here."],
            sources: ["backend-preview"],
        },
        {
            title: "Failing an async dispatch without orphaning the task",
            symptom: "A document has been staged and a task/reservation has been prepared, but worker submission or storage setup can fail before processing starts.",
            rootCause: "The application crosses storage, task, billing, and worker boundaries before the actor can claim work.",
            correction: "Release the reservation, mark the task failed where it exists, release idempotency state, and return an explicit storage/worker dispatch error.",
            verification: "The audited PDF-to-Markdown async path contains explicit failure branches; a live fault-injection run was not performed.",
            classification: "IMPLEMENTED",
            limitations: ["This is an implementation boundary, not proof that every failure combination has been exercised.", "No production retry-rate or recovery-time claim is made."],
            sources: ["backend-markdown", "backend-task"],
        },
    ],
    limitations: [
        "Evidence is based on the remote default branches audited at the recorded commits: pdfnest main 70db8e8a5a1466ddb154112ed1ddecee6e6cb57e, pdfnest-backend master 9faae1a42155843e0e5a6e472d6a4109ccaa25a8, pdfnest-worker main 9d38852e7ca1e7b657f7f644823d400553886ff0, and platen-document main a5a14413ded0daa93a5839b86554f1fe67d92a93.",
        "The source confirms implemented boundaries and defaults, not a deployed production topology, operational SLO, or universal capacity result.",
        "No numeric throughput, latency, memory, or horizontal-scaling claim is promoted because no controlled, portable measurement was found in the audited material.",
        "Some route families process locally in Go while others delegate to the worker; the evidence intentionally describes representative boundaries rather than claiming every PDF operation follows one path.",
        "The worker and Go task layers retain compatibility state shapes with different default retention windows; this is documented rather than collapsed into one invented lifecycle number.",
        "Focused code excerpts and technical screenshots remain deferred; the source links identify the exact evidence commits for later review.",
    ],
    sources: [
        {
            id: "frontend-api",
            label: "Platen PDF frontend API boundary",
            url: sourceUrl("pdfnest", PLATEN_PDF_FRONTEND_COMMIT, "lib/api.ts"),
            commit: PLATEN_PDF_FRONTEND_COMMIT,
            date: "2026-09-21",
            description: "Configured API origin, multipart blob requests, error/health handling, and download-origin checks.",
        },
        {
            id: "frontend-jobs",
            label: "Platen PDF frontend job client",
            url: sourceUrl("pdfnest", PLATEN_PDF_FRONTEND_COMMIT, "lib/editorJobs.ts"),
            commit: PLATEN_PDF_FRONTEND_COMMIT,
            date: "2026-09-21",
            description: "Editor job submission, status polling, terminal states, cancellation, and stall timeout behavior.",
        },
        {
            id: "frontend-workspace",
            label: "Platen PDF workspace route",
            url: sourceUrl("pdfnest", PLATEN_PDF_FRONTEND_COMMIT, "app/(site)/[toolId]/workspace/page.tsx"),
            commit: PLATEN_PDF_FRONTEND_COMMIT,
            date: "2026-09-21",
            description: "Shared tool workspace selection and backend availability boundary.",
        },
        {
            id: "backend-main",
            label: "Platen PDF Go API composition root",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "main.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "API body/time limits, database/Redis startup, route registration, cleanup workers, and service composition.",
        },
        {
            id: "backend-validation",
            label: "Go upload validation",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/uploads/validation.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "PDF magic-header, page-count, and operation-specific limit checks.",
        },
        {
            id: "backend-upload",
            label: "Go upload staging and cleanup",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/uploads/middleware.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Private staged upload paths, restrictive permissions, failure cleanup, and request cleanup.",
        },
        {
            id: "backend-task",
            label: "Go task registry",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/tasks/tasks.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Task state, TTL, stale transitions, cancellation, owner identity, and download-token fields.",
        },
        {
            id: "backend-download",
            label: "Go task artifact download",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/tasks/download_controller.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Completed-only, owner/token-authorized artifact serving and temporary cloud-download cleanup.",
        },
        {
            id: "backend-worker",
            label: "Go worker HTTP client",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/worker/client.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Signed worker requests, long operation timeout, and streaming multipart request construction.",
        },
        {
            id: "backend-ocr",
            label: "Go OCR controller",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/ocr/controller.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Synchronous and asynchronous OCR paths, cancellation polling, admission, result storage, billing release, and cleanup.",
        },
        {
            id: "backend-markdown",
            label: "Go async PDF-to-Markdown route",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/conversion/pdfToMarkdown.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Validation, source-object staging, task registration, worker actor dispatch, and explicit dispatch failure handling.",
        },
        {
            id: "backend-preview",
            label: "Go preview session service",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/conversion/pageToImageStream.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Owner/content-keyed preview sessions, page rendering, session touch, recreation, and temporary PDF cleanup.",
        },
        {
            id: "backend-editor-worker",
            label: "Go editor worker adapter",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/edit/python.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Editor extraction/compile job submission, status, cancellation, and download boundary.",
        },
        {
            id: "backend-storage",
            label: "Go storage boundary",
            url: sourceUrl("pdfnest-backend", PLATEN_PDF_BACKEND_COMMIT, "internal/storage/storage.go"),
            commit: PLATEN_PDF_BACKEND_COMMIT,
            date: "2026-09-20",
            description: "Application-controlled object/local storage abstraction used by async artifacts.",
        },
        {
            id: "worker-main",
            label: "Platen PDF worker application",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/main.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "FastAPI composition, worker authentication middleware, readiness checks, janitor, render pool, and route registration.",
        },
        {
            id: "worker-config",
            label: "Worker runtime guardrails",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/core/config.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Storage mode, job TTL, stale timeout, heavy-execution limits, lease settings, and managed-environment validation.",
        },
        {
            id: "worker-jobs",
            label: "Worker job model",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/jobs/models.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Queue names, queued/running/cancelled/terminal states, progress, artifacts, errors, ownership, and page status.",
        },
        {
            id: "worker-store",
            label: "Worker job store and task mirror",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/jobs/store.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Redis persistence, optimistic updates, sticky cancellation/terminal state, stale-job transition, and Go task mirror.",
        },
        {
            id: "worker-router",
            label: "Worker job submission routes",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/jobs/router.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Worker job status/cancellation and named actor submission boundary.",
        },
        {
            id: "worker-actors",
            label: "Worker processing actors",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/jobs/actors.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "OCR, searchable PDF, editor, markup, and PDF-to-Markdown queue actors with cancellation, retries, artifacts, and cleanup.",
        },
        {
            id: "worker-ocr",
            label: "Worker direct OCR routes",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/api/tools/ocr/router.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Synchronous OCR routes, temporary files, direct OCR admission, disconnect cancellation, and response cleanup.",
        },
        {
            id: "worker-ocr-v2",
            label: "Worker OCR V2 boundary",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/api/ocr_v2/router.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Private authenticated OCR V2 input staging, byte/page validation, page-scoped preview derivative, capability reporting, and safe error mapping.",
        },
        {
            id: "worker-storage",
            label: "Worker storage boundary",
            url: sourceUrl("pdfnest-worker", PLATEN_PDF_WORKER_COMMIT, "app/core/storage.py"),
            commit: PLATEN_PDF_WORKER_COMMIT,
            date: "2026-09-16",
            description: "Local/remote artifact storage abstraction, object-key handling, and worker-side materialization boundary.",
        },
        {
            id: "sdk-api",
            label: "platen-document public API",
            url: sourceUrl("platen-document", PLATEN_DOCUMENT_COMMIT, "src/platen_document/api/engine.py"),
            commit: PLATEN_DOCUMENT_COMMIT,
            date: "2026-09-18",
            description: "DocumentProcessor API, native/scanned routing, callbacks, searchable-PDF result reuse, markup, and local capability boundary.",
        },
        {
            id: "sdk-architecture",
            label: "platen-document architecture",
            url: sourceUrl("platen-document", PLATEN_DOCUMENT_COMMIT, "docs/architecture.md"),
            commit: PLATEN_DOCUMENT_COMMIT,
            date: "2026-09-18",
            description: "Explicit SDK/application boundary, supported consumer selectors, and excluded auth/job/storage concerns.",
        },
    ],
});
