import {
    validateProjectTechnicalEvidence,
    type ProjectTechnicalEvidence,
} from "./project-evidence.ts";

const POLYSHOP_COMMIT = "2e818de0c772fd186da27640933da71d1cda43e5";
const repositoryUrl = (path = "") => `https://github.com/gimesha-adikari/PolyShop/blob/${POLYSHOP_COMMIT}/${path}`;
const treeUrl = (path = "") => `https://github.com/gimesha-adikari/PolyShop/tree/${POLYSHOP_COMMIT}/${path}`;

export const polyshopTechnicalEvidence: ProjectTechnicalEvidence = validateProjectTechnicalEvidence({
    introduction: "PolyShop is recorded here as a source-audited distributed-systems lab. The repository has named service, gateway, shared-contract, infrastructure, and QA boundaries, but executable depth is uneven: auth is implemented in this snapshot, while much of the commerce workflow remains scaffolded or documented as design.",
    ownership: [
        {
            boundary: "Authentication and token authority",
            owner: "auth-service",
            responsibility: "Own user, role, token, ban, and audit entities; expose authentication/admin controllers; sign RS256 access JWTs and persist hashed token records.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "auth-jwt", "auth-token", "auth-domain"],
        },
        {
            boundary: "Commerce service boundaries",
            owner: "services/*",
            responsibility: "Separate product, inventory, order, payment, notification, search, and analytics areas are present as repository/build boundaries; most are bootstrap-only in the audited commit.",
            classification: "IMPLEMENTED",
            sources: ["service-layout", "service-builds", "service-inventory"],
        },
        {
            boundary: "Public API gateway",
            owner: "gateway",
            responsibility: "Provide the intended public entry point and route map, with Spring Cloud Gateway declared as a dependency; executable routes and filters were not found.",
            classification: "DESIGNED / PLANNED",
            sources: ["gateway-source", "gateway-build", "gateway-design"],
        },
        {
            boundary: "Shared contracts and transport helpers",
            owner: "common-libs",
            responsibility: "Define OpenAPI schemas, request/error shapes, request IDs, idempotency headers, and cross-language event payload types.",
            classification: "IMPLEMENTED",
            sources: ["openapi-contracts", "common-java-contracts", "common-js-contracts", "common-py-contracts"],
        },
        {
            boundary: "Infrastructure and verification assets",
            owner: "infra and qa",
            responsibility: "Describe local Compose/Kubernetes resources and provide Pact, Postman/Newman, and k6 test assets without claiming that they were executed.",
            classification: "NOT TESTED",
            sources: ["docker-compose", "kubernetes", "pact-assets", "postman-assets", "k6-assets"],
        },
    ],
    ipc: [
        {
            boundary: "Auth HTTP boundary",
            behavior: "AuthController exposes register, login, refresh, logout, verification, restore, password-reset, and MFA endpoints under /api/v1/auth; Spring Security applies the stateless filter chain.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "auth-security"],
        },
        {
            boundary: "Auth audit event bridge",
            behavior: "DbAuditService persists an audit event and, when a KafkaTemplate is available, sends one auth.audit message; send exceptions are swallowed by the current implementation.",
            classification: "IMPLEMENTED",
            sources: ["auth-audit-kafka", "auth-domain"],
        },
        {
            boundary: "Gateway-to-service routing",
            behavior: "The route map is documented for /auth, /products, /inventory, /orders, /payments, /search, and /analytics, but the gateway source contains only the Spring Boot application bootstrap.",
            classification: "DESIGNED / PLANNED",
            sources: ["gateway-design", "gateway-source", "gateway-openapi"],
        },
        {
            boundary: "Request and idempotency context",
            behavior: "Shared Java and TypeScript helpers model X-Request-Id and Idempotency-Key propagation; endpoint-level persistence and conflict handling are not present in the audited source.",
            classification: "DESIGNED / PLANNED",
            sources: ["common-java-contracts", "common-js-contracts", "idempotency-design"],
        },
        {
            boundary: "Kafka domain messaging",
            behavior: "Order/payment/stock event names and payload types exist in shared libraries, while source search found no executable consumer and only the narrow auth audit producer.",
            classification: "DESIGNED / PLANNED",
            sources: ["event-contracts", "auth-audit-kafka", "messaging-design"],
        },
    ],
    workflows: [
        {
            title: "Auth registration and access-token lifecycle",
            entryPoint: "POST /api/v1/auth/register, /login, and /refresh",
            mode: "sync",
            owner: "auth-service",
            processing: "Registration persists the user and role; login signs an RS256 access token and stores an access-token entry; refresh validates, revokes, and rotates the opaque refresh token.",
            result: "The controller returns a token response or an explicit validation/authentication error.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "auth-jwt", "auth-token", "auth-domain"],
        },
        {
            title: "Optional auth audit emission",
            entryPoint: "Auth service audit record",
            mode: "async",
            owner: "auth-service / DbAuditService",
            processing: "Save the audit entity first, then call KafkaTemplate.send with topic auth.audit when the optional bean is available.",
            result: "The database audit record remains the local result; broker delivery is optional and its failure is ignored.",
            classification: "IMPLEMENTED",
            sources: ["auth-audit-kafka", "auth-domain"],
        },
        {
            title: "Order, reservation, and payment saga",
            entryPoint: "POST /orders through the intended gateway",
            mode: "sync",
            owner: "order-service as proposed orchestrator",
            processing: "Design documents describe product validation, stock reservation, payment initiation, payment events, and release/cancel compensation; the order-service source is bootstrap-only.",
            result: "The order saga is DESIGNED / PLANNED; an executable orchestrator was not found in this snapshot.",
            classification: "DESIGNED / PLANNED",
            sources: ["saga-design", "communication-design", "order-source", "event-contracts"],
        },
    ],
    lifecycle: [
        {
            phase: "Register",
            actor: "AuthController and UserService",
            action: "Validate the request, normalize the email, create the user/role records, create an email-verification token, and send the verification message.",
            result: "A registered account response is returned; persistence is handled by the auth JPA boundary.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "auth-user-service", "auth-domain"],
        },
        {
            phase: "Login",
            actor: "AuthController and JwtUtil",
            action: "Authenticate credentials, generate a `kid`-tagged RS256 access JWT, persist its JTI hash, and create a hashed refresh-token record.",
            result: "The client receives access and refresh tokens with an access-token TTL.",
            classification: "IMPLEMENTED",
            sources: ["auth-controller", "auth-jwt", "auth-token"],
        },
        {
            phase: "Validate or revoke",
            actor: "JwtAuthenticationFilter and AuthTokenService",
            action: "Resolve the public key by `kid`, parse the signed token, and require a non-revoked, non-expired persisted access-token entry; logout/revocation updates the record.",
            result: "Invalid or revoked access tokens do not establish the Spring Security context.",
            classification: "IMPLEMENTED",
            sources: ["auth-filter", "auth-jwt", "auth-token"],
        },
        {
            phase: "Auth audit send failure",
            actor: "DbAuditService",
            action: "Attempt the optional `auth.audit` Kafka send after saving the database audit record.",
            result: "The local audit save remains; a Kafka send exception is caught and ignored rather than retried or moved to a dead-letter path.",
            classification: "IMPLEMENTED",
            sources: ["auth-audit-kafka"],
        },
        {
            phase: "Distributed order workflow",
            actor: "Order, inventory, payment, and notification services",
            action: "The design documents describe state transitions, events, reservations, payment outcomes, retries, and compensation.",
            result: "The documented lifecycle remains a planned boundary because the participating service implementations were not found.",
            classification: "DESIGNED / PLANNED",
            sources: ["saga-design", "messaging-design", "order-source"],
        },
    ],
    processingPaths: [
        {
            title: "Implemented auth persistence path",
            boundary: "HTTP request → auth controller → JPA entity/repository",
            behavior: "Auth owns concrete user, role, token, ban, and audit entities/repositories; token hashes rather than raw opaque tokens are persisted.",
            classification: "IMPLEMENTED",
            limitations: ["This source-backed path is limited to auth; the other named domain services do not contain equivalent entities in this snapshot."],
            sources: ["auth-controller", "auth-domain", "auth-repositories"],
        },
        {
            title: "Narrow implemented Kafka path",
            boundary: "Auth audit entity → optional KafkaTemplate",
            behavior: "DbAuditService sends the audit message to `auth.audit` when a KafkaTemplate bean is available; there is no matching executable consumer in the repository.",
            classification: "IMPLEMENTED",
            limitations: ["The send is optional and failure is swallowed.", "No broker or consumer run was performed."],
            sources: ["auth-audit-kafka", "kafka-build", "source-search"],
        },
        {
            title: "Documented saga path",
            boundary: "Gateway → order → inventory/payment → events/compensation",
            behavior: "Architecture and ADR documents define a hybrid saga, event names, and compensation steps.",
            classification: "DESIGNED / PLANNED",
            limitations: ["No executable order orchestrator, consumer, outbox, reservation handler, or payment integration was found."],
            sources: ["saga-design", "communication-design", "outbox-design"],
        },
        {
            title: "QA asset path",
            boundary: "Pact/Postman/k6 files → external test runner",
            behavior: "The repository contains contract, API collection, Newman, and k6 assets intended to be run against services.",
            classification: "NOT TESTED",
            limitations: ["No dependency installation, service startup, test run, report, or threshold result was observed."],
            sources: ["pact-assets", "postman-assets", "newman-assets", "k6-assets"],
        },
    ],
    failureBoundaries: [
        {
            boundary: "Access-token validity",
            trigger: "The JWT is missing, has an unknown key ID, cannot be parsed, or has no valid persisted JTI entry.",
            behavior: "JwtAuthenticationFilter leaves the request unauthenticated so Spring Security can reject protected routes.",
            classification: "IMPLEMENTED",
            sources: ["auth-filter", "auth-jwt", "auth-security"],
        },
        {
            boundary: "Auth abuse windows",
            trigger: "IP, email, or phone counters exceed their configured in-memory window; a persistent ban is also present.",
            behavior: "RateLimitFilter returns a 429 response for the relevant rate limit or 403 for a ban.",
            classification: "IMPLEMENTED",
            sources: ["auth-rate", "auth-brute-force"],
        },
        {
            boundary: "Audit broker send",
            trigger: "The optional Kafka audit send raises an exception.",
            behavior: "The exception is ignored after the database audit attempt; no retry or dead-letter behavior is implemented in this path.",
            classification: "IMPLEMENTED",
            sources: ["auth-audit-kafka"],
        },
        {
            boundary: "Gateway reachability",
            trigger: "A client needs a routed service or a normalized gateway error.",
            behavior: "The intended route/error behavior is described in docs and schemas, but no executable gateway route/filter was found to verify the failure response.",
            classification: "NOT TESTED",
            sources: ["gateway-source", "gateway-design", "gateway-openapi"],
        },
        {
            boundary: "Saga compensation",
            trigger: "Stock reservation or payment would fail or time out in the documented order workflow.",
            behavior: "Release-stock and cancel-order actions are described as planned compensation; the executable handlers were not found.",
            classification: "DESIGNED / PLANNED",
            sources: ["saga-design", "communication-design"],
        },
    ],
    decisions: [
        {
            title: "Keep service boundaries evidence-scoped",
            choice: "Present the named service directories as repository ownership boundaries, while explicitly showing that only auth has substantial implementation in this snapshot.",
            rationale: "The directory/build structure is real evidence, but naming a microservice is not enough to imply a running independently implemented service.",
            alternative: "Treat every service directory as a completed production component; rejected because source inventory shows bootstrap-only areas.",
            classification: "ACCEPTED",
            sources: ["service-layout", "service-inventory"],
        },
        {
            title: "Limit Kafka wording to executable source",
            choice: "Describe one optional auth audit producer plus shared event contracts; keep the broader consumer topology as planned.",
            rationale: "The source contains a KafkaTemplate send but no executable consumer or order-event runtime path.",
            alternative: "Publish the README topic topology as implemented; rejected because documentation/configuration is not execution evidence.",
            classification: "ACCEPTED",
            sources: ["auth-audit-kafka", "event-contracts", "source-search"],
        },
        {
            title: "Do not publish a Redis runtime claim",
            choice: "Describe Redis as declared infrastructure/design material and call out that the implemented auth limiter is process-local.",
            rationale: "Static source search found no Redis client or template; the actual rate limiter uses ConcurrentHashMap.",
            alternative: "Repeat the README's sessions/rate-limit/idempotency wording; rejected because it exceeds source evidence.",
            classification: "ACCEPTED",
            sources: ["auth-rate", "docker-compose", "redis-design", "source-search"],
        },
        {
            title: "Keep the order saga as designed",
            choice: "Show the proposed hybrid saga and compensation boundaries with a DESIGNED / PLANNED badge, not as an implemented workflow.",
            rationale: "The order service has no controller, domain, repository, producer, or consumer source in the audited commit.",
            alternative: "Describe Order Service as the working orchestrator; rejected because only ADR/sequence documentation establishes it.",
            classification: "ACCEPTED",
            sources: ["saga-design", "order-source", "outbox-design"],
        },
        {
            title: "Keep PolyShop secondary",
            choice: "Retain `featured: false` and expose the evidence record on the detail page without adding PolyShop to homepage flagship selectors.",
            rationale: "The audit found useful architecture and QA artifacts, but not enough executable distributed-system or operational evidence for flagship promotion.",
            alternative: "Promote PolyShop as a fourth flagship from README claims; rejected pending deeper evidence.",
            classification: "ACCEPTED",
            sources: ["readme", "service-layout", "pact-assets", "postman-assets", "k6-assets", "repo-root"],
        },
    ],
    measurements: [
        {
            claim: "Implementation depth by service",
            result: "The bounded source inventory found four auth controllers, five auth entities, and five auth repositories; inventory, order, product, search, and gateway have no controllers/entities/repositories in the audited source. Analytics and notification are two-route FastAPI stubs; payment is an Express scaffold.",
            context: "Static review of the public main snapshot at the pinned commit.",
            classification: "ACCEPTED",
            method: "Enumerate tracked application source and inspect controller/entity/repository/module declarations.",
            environment: "Fresh read-only shallow clone of public gimesha-adikari/PolyShop main; no services started.",
            sample: "All service and gateway application source files present at commit 2e818de0c772fd186da27640933da71d1cda43e5.",
            limitations: ["A source inventory is not a runtime health or deployment measurement.", "Generated/external dependencies were not treated as implementation evidence."],
            sources: ["service-layout", "service-inventory", "auth-domain"],
        },
        {
            claim: "Pact contract-test assets",
            result: "Pact TypeScript/JavaScript consumer/provider files and package configuration are present; Pact was not executed in this audit.",
            context: "QA asset inspection only.",
            classification: "NOT TESTED",
            method: "Read the Pact package, consumer interactions, provider setup/state files, and test runner configuration.",
            environment: "Read-only repository audit; no Pact dependencies or service endpoints started.",
            sample: "Four TypeScript interaction files plus JavaScript/provider assets under qa/pact-tests.",
            limitations: ["Presence of test code is not a passing contract result.", "The interactions target endpoints not implemented by the audited service scaffolds."],
            sources: ["pact-assets"],
        },
        {
            claim: "k6 performance scenarios",
            result: "Smoke, load, stress, spike, and soak scripts exist; load-test.js declares p95<350 ms and failure rate<1% thresholds, but k6 was not run and no output was found.",
            context: "Scenario/threshold inspection only.",
            classification: "NOT TESTED",
            method: "Read the k6 options, stages, checks, and thresholds; search the repository for result artifacts.",
            environment: "Read-only repository audit; no gateway or service runtime started.",
            sample: "Five scenario scripts under qa/performance-tests.",
            limitations: ["A threshold is not a measurement.", "No latency, throughput, capacity, or scaling conclusion is published."],
            sources: ["k6-assets"],
        },
        {
            claim: "Runtime integration",
            result: "Docker Compose, Dockerfiles, and Kubernetes manifests describe intended resources, but no container build, Compose health check, Kubernetes rollout, or end-to-end request run was performed.",
            context: "Infrastructure artifact review.",
            classification: "NOT TESTED",
            method: "Inspect Compose services, image/Dockerfile entrypoints, health checks, Kubernetes probes, and repository completeness.",
            environment: "Read-only source audit; external repository was not modified or deployed.",
            sample: "infra/docker/compose, service/gateway Dockerfiles, and infra/k8s/base manifests.",
            limitations: ["Several Dockerfiles reference absent files or paths in this snapshot.", "No operational claim is made from declarative manifests."],
            sources: ["docker-compose", "dockerfiles", "kubernetes"],
        },
    ],
    debuggingStories: [
        {
            title: "README claims versus the current tree",
            symptom: "README describes GitHub Actions, a TypeScript SDK path, and broad service capabilities that do not all appear in the current tree.",
            rootCause: "The README and design documents contain intended or historical architecture alongside a sparse current implementation snapshot.",
            correction: "The portfolio evidence separates source-backed implementation, test assets, configuration, and design-only material instead of treating the README as runtime proof.",
            verification: "The current root, service inventory, .github path, and referenced files were checked at the pinned commit.",
            classification: "ACCEPTED",
            limitations: ["This audit does not rewrite the external README.", "Future commits may change the evidence state."],
            sources: ["readme", "repo-root", "service-inventory"],
        },
        {
            title: "Redis wording versus the implemented limiter",
            symptom: "README and infrastructure docs mention Redis for sessions, rate limiting, and idempotency, while the auth limiter uses an in-memory map.",
            rootCause: "The Redis design/configuration is ahead of the executable service code in the audited snapshot.",
            correction: "Portfolio wording identifies Redis as planned infrastructure and calls the actual rate limit behavior process-local.",
            verification: "Source search found no RedisTemplate, StringRedisTemplate, Lettuce, Jedis, or RedisConnection use; RateLimitService uses ConcurrentHashMap.",
            classification: "ACCEPTED",
            limitations: ["Static search cannot prove behavior in unavailable generated/external code.", "No Redis runtime was started."],
            sources: ["auth-rate", "docker-compose", "redis-design", "source-search"],
        },
    ],
    limitations: [
        "The audited public main commit is source evidence only; no claim is made about later commits or private work.",
        "Only auth has substantial executable domain/controller/persistence code in this snapshot; the other named services are mostly scaffolds or stubs.",
        "Gateway routes, gateway authentication, gateway rate limiting, CORS, request IDs, and OpenAPI aggregation are documented or declared but not implemented in the gateway source inspected.",
        "Kafka evidence is limited to one optional auth audit producer and shared contracts; no executable consumer topology was found.",
        "Redis client usage was not found; the implemented auth rate limiter is process-local.",
        "The order saga, compensation, outbox, retries, and dead-letter flow are design material; an executable orchestrator was not found.",
        "Pact/Postman/Newman/k6 are test assets only in this record; no passing report or measured performance output is attached.",
        "No `.github/workflows` directory is present at the audited commit, so CI/CD execution is not claimed.",
        "Docker and Kubernetes artifacts were not built, applied, or health-checked; declarative manifests do not establish deployment.",
        "No production operation, capacity, scalability, availability, or external-provider outcome is claimed.",
    ],
    sources: [
        {
            id: "repo-root",
            label: "PolyShop audited main snapshot",
            url: treeUrl(),
            commit: POLYSHOP_COMMIT,
            date: "2025-11-19",
            description: "Public repository root and current main tree used as the audit boundary.",
        },
        {
            id: "readme",
            label: "PolyShop README",
            url: repositoryUrl("README.md"),
            commit: POLYSHOP_COMMIT,
            description: "README claims and documented intended architecture, kept separate from executable evidence.",
        },
        {
            id: "service-layout",
            label: "Service directory layout",
            url: treeUrl("services"),
            commit: POLYSHOP_COMMIT,
            description: "Named service directories and their public repository boundary.",
        },
        {
            id: "service-builds",
            label: "Service build declarations",
            url: repositoryUrl("services/order-service/build.gradle.kts"),
            commit: POLYSHOP_COMMIT,
            description: "Representative Spring Boot/JPA/Cloud dependency declarations for a scaffolded service.",
        },
        {
            id: "service-inventory",
            label: "Application source inventory",
            url: treeUrl("services"),
            commit: POLYSHOP_COMMIT,
            description: "Bounded audit of controllers, entities, repositories, Python routes, and the payment scaffold.",
        },
        {
            id: "order-source",
            label: "Order service bootstrap",
            url: repositoryUrl("services/order-service/src/main/java/com/polyshop/orderservice/OrderServiceApplication.java"),
            commit: POLYSHOP_COMMIT,
            description: "The audited order-service application entry point; no order controller, domain, repository, or orchestrator accompanies it.",
        },
        {
            id: "auth-controller",
            label: "Auth controller",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/controller/AuthController.java"),
            commit: POLYSHOP_COMMIT,
            description: "Register, login, refresh, logout, verification, restore, password reset, and MFA endpoints.",
        },
        {
            id: "auth-security",
            label: "Auth security configuration",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/config/SecurityConfig.java"),
            commit: POLYSHOP_COMMIT,
            description: "Stateless Spring Security filter chain, public auth paths, and protected routes.",
        },
        {
            id: "auth-jwt",
            label: "JWT signing and key resolution",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/security/JwtUtil.java"),
            commit: POLYSHOP_COMMIT,
            description: "RS256 access-token generation, issuer, key ID, JTI, and public-key resolution boundary.",
        },
        {
            id: "auth-filter",
            label: "JWT authentication filter",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/security/JwtAuthenticationFilter.java"),
            commit: POLYSHOP_COMMIT,
            description: "JWT parse/JTI validation and Spring Security context population.",
        },
        {
            id: "auth-token",
            label: "Persisted token service",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/service/impl/AuthTokenServiceImpl.java"),
            commit: POLYSHOP_COMMIT,
            description: "Hashed opaque token creation, refresh rotation, revocation, access-token validity, and cleanup-facing persistence.",
        },
        {
            id: "auth-domain",
            label: "Auth domain entities",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/domain/AuthToken.java"),
            commit: POLYSHOP_COMMIT,
            description: "Representative auth JPA entity; the auth service also contains User, Role, Ban, and AuditEvent entities.",
        },
        {
            id: "auth-user-service",
            label: "Auth user service",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/service/impl/UserServiceImpl.java"),
            commit: POLYSHOP_COMMIT,
            description: "User registration/authentication, password handling, role assignment, account state, and token revocation calls.",
        },
        {
            id: "auth-repositories",
            label: "Auth repositories",
            url: treeUrl("services/auth-service/src/main/java/com/polyshop/authservice/repository"),
            commit: POLYSHOP_COMMIT,
            description: "JPA repositories for users, roles, tokens, bans, and audit events.",
        },
        {
            id: "auth-rate",
            label: "Auth rate-limit filter/service",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/security/RateLimitService.java"),
            commit: POLYSHOP_COMMIT,
            description: "Process-local ConcurrentHashMap counters used by the auth request filter.",
        },
        {
            id: "auth-brute-force",
            label: "Auth brute-force bans",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/security/BruteForceService.java"),
            commit: POLYSHOP_COMMIT,
            description: "Database-backed ban lookup/expiry behavior used by the rate-limit filter.",
        },
        {
            id: "auth-audit-kafka",
            label: "Auth audit Kafka producer",
            url: repositoryUrl("services/auth-service/src/main/java/com/polyshop/authservice/service/impl/DbAuditService.java"),
            commit: POLYSHOP_COMMIT,
            description: "The narrow executable KafkaTemplate send found during source search.",
        },
        {
            id: "kafka-build",
            label: "Auth Kafka dependencies",
            url: repositoryUrl("services/auth-service/build.gradle.kts"),
            commit: POLYSHOP_COMMIT,
            description: "Spring Kafka and Kafka Streams dependencies declared by auth-service.",
        },
        {
            id: "source-search",
            label: "Source-level messaging/cache boundary",
            url: treeUrl(),
            commit: POLYSHOP_COMMIT,
            description: "Repository-wide source audit for Kafka consumers, Redis clients, saga handlers, and outbox implementation.",
        },
        {
            id: "event-contracts",
            label: "Shared event contracts",
            url: repositoryUrl("common-libs/common-java/src/main/java/com/polyshop/common/events/OrderEvents.java"),
            commit: POLYSHOP_COMMIT,
            description: "Java order event names/payloads, with parallel TypeScript/Python contract assets.",
        },
        {
            id: "common-java-contracts",
            label: "Shared Java request/error helpers",
            url: repositoryUrl("common-libs/common-java/src/main/java/com/polyshop/common/http/RequestIdFilter.java"),
            commit: POLYSHOP_COMMIT,
            description: "Request ID filter, shared error handler, event envelope, and common helper boundary.",
        },
        {
            id: "common-js-contracts",
            label: "Shared TypeScript request/event contracts",
            url: repositoryUrl("common-libs/common-js/src/http/request-context.ts"),
            commit: POLYSHOP_COMMIT,
            description: "Request ID, idempotency key, bearer header, DTO, and event type assets.",
        },
        {
            id: "common-py-contracts",
            label: "Shared Python event contracts",
            url: repositoryUrl("common-libs/common-py/events.py"),
            commit: POLYSHOP_COMMIT,
            description: "Pydantic event envelope and event type constants for Python consumers/producers.",
        },
        {
            id: "gateway-source",
            label: "Gateway bootstrap",
            url: repositoryUrl("gateway/src/main/java/com/polyshop/gateway/GatewayApplication.java"),
            commit: POLYSHOP_COMMIT,
            description: "Gateway application entry point; no route/controller/filter source accompanies it.",
        },
        {
            id: "gateway-build",
            label: "Gateway dependencies",
            url: repositoryUrl("gateway/build.gradle.kts"),
            commit: POLYSHOP_COMMIT,
            description: "Spring Cloud Gateway, load-balancer, actuator, security, and circuit-breaker declarations.",
        },
        {
            id: "gateway-design",
            label: "Gateway routing design",
            url: repositoryUrl("docs/decision-records/ADR-0011-api-gateway-routing.md"),
            commit: POLYSHOP_COMMIT,
            description: "Documented route, token, rate-limit, error, and OpenAPI aggregation intent.",
        },
        {
            id: "gateway-openapi",
            label: "Gateway OpenAPI asset",
            url: repositoryUrl("common-libs/api-schemas/gateway.yaml"),
            commit: POLYSHOP_COMMIT,
            description: "OpenAPI route/schema asset for the intended public gateway surface.",
        },
        {
            id: "openapi-contracts",
            label: "OpenAPI service contracts",
            url: treeUrl("common-libs/api-schemas"),
            commit: POLYSHOP_COMMIT,
            description: "OpenAPI 3.1 schemas for the gateway and named services.",
        },
        {
            id: "idempotency-design",
            label: "Idempotency design",
            url: repositoryUrl("docs/decision-records/ADR-0016-idempotency-strategy.md"),
            commit: POLYSHOP_COMMIT,
            description: "Intended key, request-hash, response-cache, consumer, payment, and reservation policy.",
        },
        {
            id: "saga-design",
            label: "Order saga design",
            url: repositoryUrl("docs/architecture/sequence/order-saga-workflow.md"),
            commit: POLYSHOP_COMMIT,
            description: "Documented order state machine, participant responsibilities, timeout, and compensation intent.",
        },
        {
            id: "communication-design",
            label: "Communication design",
            url: repositoryUrl("docs/architecture/communication.md"),
            commit: POLYSHOP_COMMIT,
            description: "Documented gateway/service routes, synchronous calls, Kafka topology, and order workflow.",
        },
        {
            id: "messaging-design",
            label: "Messaging design",
            url: repositoryUrl("docs/architecture/polyshop-outbox-and-messaging.md"),
            commit: POLYSHOP_COMMIT,
            description: "Outbox, processed-events, retry, DLT, envelope, and consumer-idempotency design document.",
        },
        {
            id: "outbox-design",
            label: "Outbox design",
            url: repositoryUrl("docs/architecture/polyshop-outbox-and-messaging.md"),
            commit: POLYSHOP_COMMIT,
            description: "Design-only outbox schema and publisher algorithm.",
        },
        {
            id: "redis-design",
            label: "Redis design/configuration",
            url: repositoryUrl("infra/docker/compose/docker-compose.dev.yml"),
            commit: POLYSHOP_COMMIT,
            description: "Local Redis container and environment declarations, not executable client usage.",
        },
        {
            id: "pact-assets",
            label: "Pact test assets",
            url: treeUrl("qa/pact-tests"),
            commit: POLYSHOP_COMMIT,
            description: "Pact package, consumers, provider setup/states, and verification test files.",
        },
        {
            id: "postman-assets",
            label: "Postman collections",
            url: repositoryUrl("qa/postman/PolyShop.postman_collection.json"),
            commit: POLYSHOP_COMMIT,
            description: "Full API collection with service-oriented request examples.",
        },
        {
            id: "newman-assets",
            label: "Newman runners",
            url: repositoryUrl("qa/newman/run-tests.sh"),
            commit: POLYSHOP_COMMIT,
            description: "Newman command/report runner scripts; no generated report is attached.",
        },
        {
            id: "k6-assets",
            label: "k6 scenarios",
            url: repositoryUrl("qa/performance-tests/load-test.js"),
            commit: POLYSHOP_COMMIT,
            description: "Load scenario with stages/checks/thresholds, plus smoke/stress/spike/soak files.",
        },
        {
            id: "docker-compose",
            label: "Docker Compose development topology",
            url: repositoryUrl("infra/docker/compose/docker-compose.dev.yml"),
            commit: POLYSHOP_COMMIT,
            description: "Declared local services, databases, Kafka/Zookeeper, Redis, MailHog, and OpenSearch.",
        },
        {
            id: "dockerfiles",
            label: "Service Dockerfiles",
            url: repositoryUrl("gateway/Dockerfile"),
            commit: POLYSHOP_COMMIT,
            description: "Representative multi-stage image and health-check declarations; not built in this audit.",
        },
        {
            id: "kubernetes",
            label: "Kubernetes base manifests",
            url: treeUrl("infra/k8s/base"),
            commit: POLYSHOP_COMMIT,
            description: "Deployments, Services, ingress, HPAs, ConfigMap, and example Secret manifests.",
        },
        {
            id: "observability-design",
            label: "Observability design",
            url: repositoryUrl("docs/decision-records/ADR-0005-logging-and-observability.md"),
            commit: POLYSHOP_COMMIT,
            description: "Documented JSON logging, Prometheus/Grafana/Loki, OpenTelemetry/Jaeger, and SLO intent.",
        },
    ],
});
